const fs=require('node:fs'),os=require('node:os'),path=require('node:path'),net=require('node:net'),assert=require('node:assert/strict');
const {spawn,execFileSync}=require('node:child_process');
const runtime=process.env.QL_BROWSER_RUNTIME||'/tmp/qinglong-phase45b-browser/node_modules';
const {chromium}=require(path.join(runtime,'playwright')), {Server,utils}=require(path.join(runtime,'ssh2'));
const root=path.resolve(__dirname,'../..'),tmp=fs.mkdtempSync(path.join(os.tmpdir(),'platform-full-'));
const delay=ms=>new Promise(r=>setTimeout(r,ms));
const evidence={status:'RUNNING',steps:[],linux:process.platform==='linux'};
let backend,browser,ssh,packageIndex,nodeRegistry,output='',page;const connections=new Set();
const mark=name=>{evidence.steps.push(name);console.log(name);};
async function port(){const s=net.createServer();await new Promise(r=>s.listen(0,'127.0.0.1',r));const p=s.address().port;await new Promise(r=>s.close(r));return p;}
async function stop(){if(!backend)return;const cp=backend;backend=null;try{process.kill(-cp.pid,'SIGTERM')}catch{}for(let i=0;i<40&&cp.exitCode===null;i++)await delay(100);try{process.kill(-cp.pid,'SIGKILL')}catch{}}
async function until(fn){const deadline=Date.now()+60000;let last;while(Date.now()<deadline){try{const value=await fn();if(value)return value;}catch(e){last=e;}await delay(200);}throw last||new Error('poll timeout');}
(async()=>{
 fs.chmodSync(tmp,0o700);
 for(const d of ['shell','sample'])fs.cpSync(path.join(root,d),path.join(tmp,d),{recursive:true});
 fs.copyFileSync(path.join(root,'version.yaml'),path.join(tmp,'version.yaml'));
 fs.symlinkSync(path.join(root,'node_modules'),path.join(tmp,'node_modules'));fs.mkdirSync(path.join(tmp,'back'));fs.symlinkSync(path.join(root,'back/protos'),path.join(tmp,'back/protos'));
 fs.mkdirSync(path.join(tmp,'static'));for(const d of ['build','dist'])fs.symlinkSync(path.join(root,'static',d),path.join(tmp,'static',d));
 fs.mkdirSync(path.join(tmp,'home'));fs.mkdirSync(path.join(tmp,'bin'));
 fs.symlinkSync(path.join(tmp,'shell/task.sh'),path.join(tmp,'bin/task'));fs.symlinkSync(path.join(tmp,'shell/update.sh'),path.join(tmp,'bin/ql'));
 fs.writeFileSync(path.join(tmp,'.env'),'JWT_SECRET=local-e2e-only-backend-secret\n');
 const origin=path.join(tmp,'origin');fs.mkdirSync(origin);
 const git=(...args)=>execFileSync('git',args,{cwd:origin,stdio:'pipe'});
 git('init','-b','main');git('config','user.name','Fixture');git('config','user.email','fixture@example.invalid');
 const scripts={
 js:'const fs=require("fs"); console.log("E2E_NODE:"+process.env.GLOBAL_VALUE+":"+process.env.PROFILE_VALUE+":"+process.env.TASK_VALUE); console.log("CONFIG_OK:"+fs.readFileSync("config.txt","utf8")); if(fs.existsSync("secret.txt"))console.log(fs.readFileSync("secret.txt","utf8")); console.log(process.env.HOOK_TOKEN);',
 py:'import os\nprint("E2E_PYTHON:"+os.environ["GLOBAL_VALUE"]+":"+os.environ["PROFILE_VALUE"]+":"+os.environ["TASK_VALUE"])\nprint("CONFIG_OK:"+open("config.txt").read())\nif os.path.exists("secret.txt"): print(open("secret.txt").read())\nprint(os.environ["HOOK_TOKEN"])',
 sh:'printf "E2E_SHELL:%s:%s:%s\\n" "$GLOBAL_VALUE" "$PROFILE_VALUE" "$TASK_VALUE"; printf "CONFIG_OK:"; cat config.txt; [ ! -f secret.txt ] || cat secret.txt; printf "\\n%s\\n" "$HOOK_TOKEN"'};

 scripts.js += '\nconsole.log("MANAGED_NODE:"+process.execPath+":"+require("ql-phase8-foo"));';
 scripts.py += '\nimport sys, ql_phase7_root\nprint("MANAGED_PYTHON:"+sys.executable+":"+ql_phase7_root.__version__)';
 scripts.sh += '\nif [ "${1:-}" = "--sleep" ]; then sleep 30; fi';
 for(const [ext,body]of Object.entries(scripts))fs.writeFileSync(path.join(origin,`job.${ext}`),`${ext==='js'?'//':'#'} name: E2E ${ext}\n${ext==='js'?'//':'#'} cron: 0 0 1 1 *\n${body}\n`);
 git('add','.');git('commit','-qm','fixture');git('branch','secondary');
 for(const name of ['host','client'])execFileSync('ssh-keygen',['-q','-t','ed25519','-N','','-f',path.join(tmp,name)],{stdio:'pipe'});
 const clientKey=utils.parseKey(fs.readFileSync(path.join(tmp,'client.pub'))),hostPublic=fs.readFileSync(path.join(tmp,'host.pub'),'utf8').trim().split(' ').slice(0,2).join(' ');
 ssh=new Server({hostKeys:[fs.readFileSync(path.join(tmp,'host'))]},client=>{
  connections.add(client);client.on('error',()=>{}).on('close',()=>connections.delete(client));
  client.on('authentication',ctx=>{if(ctx.username!=='git'||ctx.method!=='publickey'||!ctx.key.data.equals(clientKey.getPublicSSH())||(ctx.signature&&clientKey.verify(ctx.blob,ctx.signature,ctx.hashAlgo)!==true))return ctx.reject();ctx.accept();});
  client.on('ready',()=>client.on('session',accept=>accept().on('exec',(accept,reject,info)=>{
   if(info.command!=="git-upload-pack '/fixture.git'")return reject();const stream=accept();const cp=spawn('git-upload-pack',[origin],{stdio:['pipe','pipe','pipe']});stream.pipe(cp.stdin);cp.stdout.pipe(stream,{end:false});cp.stderr.pipe(stream.stderr,{end:false});cp.on('close',code=>{stream.exit(code||0);stream.end();});stream.on('close',()=>cp.kill());
  })));
 });
 await new Promise(r=>ssh.listen(0,'127.0.0.1',r));const sshPort=ssh.address().port, http=await port(),grpc=await port(),base=`http://127.0.0.1:${http}`;
 const env={...process.env,QL_DIR:tmp,QL_DATA_DIR:path.join(tmp,'data'),HOME:path.join(tmp,'home'),PATH:path.join(tmp,'bin')+':'+process.env.PATH,JWT_SECRET:'local-e2e-only-backend-secret',BACK_PORT:String(http),GRPC_PORT:String(grpc),BIND_HOST:'127.0.0.1',BIND_HOST_GRPC:'127.0.0.1',QL_SCHEDULER:'node',NODE_ENV:'production'};
 async function start(){backend=spawn(process.execPath,['--require',path.join(__dirname,'browser-provider.cjs'),path.join(root,'static/build/app.js')],{cwd:root,env,detached:true,stdio:['ignore','pipe','pipe']});backend.stdout.on('data',b=>output+=b);backend.stderr.on('data',b=>output+=b);await until(async()=>{const r=await fetch(base+'/api/system');return(await r.json()).code===200;});}
 packageIndex=await require('../../tests/phase7/wheelhouse.cjs').wheelhouse(path.join(tmp,'wheelhouse'));env.QL_PHASE7_TEST_INDEX=packageIndex.index;
 nodeRegistry=await require('../../tests/phase8/registry.cjs').registry();env.QL_PHASE8_TEST_REGISTRY=nodeRegistry.url;
 await start();mark('empty-root-bootstrap');
 browser=await chromium.launch({headless:true,...(process.platform==='darwin'?{channel:'chrome'}:{})});page=await browser.newPage({locale:'zh-CN',viewport:{width:1440,height:1100}});page.setDefaultTimeout(20000);
 const forbidden=['local-e2e-only-backend-secret','CONFIG_SECRET_E2E','generated-private-e2e','ENV_SECRET_E2E'];const leaks=[];const inspected=[];let websocketFrames=0;page.on('websocket',socket=>socket.on('framereceived',event=>{websocketFrames++;if(forbidden.some(value=>String(event.payload).includes(value)))leaks.push('websocket:'+new URL(socket.url()).pathname);}));page.on('response',async response=>{if(!response.url().includes('/api/'))return;try{const body=await response.text();inspected.push(response.url());if(forbidden.some(value=>body.includes(value)))leaks.push(new URL(response.url()).pathname);}catch{}});
 await page.goto(base);await page.getByRole('button',{name:'开始安装',exact:true}).click();await page.getByRole('button',{name:'跳过',exact:true}).click();
 await page.getByLabel('用户名',{exact:true}).fill('platform-owner');await page.getByLabel('密码',{exact:true}).fill('e2e-fixture-password');await page.getByLabel('确认密码',{exact:true}).fill('e2e-fixture-password');await page.getByRole('button',{name:/提.*交/}).click();await page.getByRole('button',{name:'去登录',exact:true}).click();
 async function login(){await page.getByLabel('用户名',{exact:true}).fill('platform-owner');await page.getByLabel('密码',{exact:true}).fill('e2e-fixture-password');await page.getByRole('button',{name:/登.*录/}).click();await until(async()=>page.evaluate(()=>!!localStorage.getItem('token')));}
 await login();mark('browser-fresh-initialize-login');
 const api=async(url,method='GET',body)=>page.evaluate(async({url,method,body})=>{const token=localStorage.getItem('token');const r=await fetch('/api'+url,{method,headers:{'content-type':'application/json',Authorization:'Bearer '+token},body:body===undefined?undefined:JSON.stringify(body)});return r.json();},{url,method,body});
 async function choose(label,text,scope=page){await scope.getByLabel(label,{exact:true}).locator('xpath=ancestor::div[contains(@class,"ant-select-selector")]').click();await page.locator('.ant-select-dropdown:visible .ant-select-item-option-content').getByText(text,{exact:true}).click();}
 async function confirm(){await page.locator('.ant-modal:visible').getByRole('button',{name:/确.*定/}).click();await page.locator('.ant-modal:visible').waitFor({state:'hidden'});}
 await page.goto(base+'/repository');await page.getByRole('tab',{name:'Credentials / 凭证'}).click();await page.getByRole('button',{name:'创建凭证'}).click();
 let modal=page.locator('.ant-modal:visible');await modal.getByLabel('名称',{exact:true}).fill('E2E SSH');await choose('认证方式','ssh_key',modal);await modal.getByLabel('SSH Private Key',{exact:true}).fill(fs.readFileSync(path.join(tmp,'client'),'utf8'));await modal.getByLabel('已验证的 known_hosts',{exact:true}).fill(`[127.0.0.1]:${sshPort} ${hostPublic}`);await confirm();mark('browser-credential-create');
 await page.getByRole('tab',{name:'Repositories / 仓库'}).click();await page.getByRole('button',{name:'创建仓库'}).click();modal=page.locator('.ant-modal:visible');await modal.getByLabel('名称',{exact:true}).fill('E2E Repo');await modal.getByLabel('Remote URL',{exact:true}).fill(`ssh://git@127.0.0.1:${sshPort}/fixture.git`);await choose('默认凭证','E2E SSH (ssh_key, enabled)',modal);await confirm();
 const repo=(await api('/repositories')).data[0];assert.ok(repo.id);mark('browser-repository-create');
 await page.goto(base+`/repository-workspace?id=${repo.id}`);
 async function repositoryAction(label,operation){
  const button=page.getByRole('button',{name:label,exact:true});let body;
  // A read-only diagnostics lease may overlap a UI click; only explicit BUSY is retryable.
  for(let attempt=0;attempt<5;attempt++){
   await until(async()=>await button.isVisible()&&!((await button.getAttribute('class'))||'').includes('loading'));
   const response=page.waitForResponse(r=>new URL(r.url()).pathname.endsWith(`/repositories/${repo.id}/${operation}`)&&r.request().method()==='POST');
   await button.click();body=await(await response).json();
   if(body.code!==409||body.error_code!=='REPOSITORY_BUSY')break;
   await delay(300);
  }
  assert.equal(body.code,200,JSON.stringify(body));await until(async()=>!((await button.getAttribute('class'))||'').includes('loading'));
 }

 await repositoryAction('Initialize','initialize');await repositoryAction('Fetch','fetch');mark('browser-initialize-fetch');
 await page.goto(base+'/subscription');await page.getByRole('button',{name:'创建订阅',exact:true}).click();modal=page.locator('.ant-modal:visible');assert.doesNotMatch(await modal.innerText(),/Legacy|Managed|Manual URL|Convert|Pull Type|Pull Option|Credential Override/i);await modal.getByLabel('名称',{exact:true}).fill('E2E Subscription');await modal.getByLabel('Repository',{exact:true}).locator('xpath=ancestor::div[contains(@class,"ant-select-selector")]').click();await page.locator('.ant-select-dropdown:visible').getByText(/E2E Repo/).click();await modal.getByLabel('Branch',{exact:true}).fill('main');await confirm();
 const sub=(await api('/subscriptions')).data[0];await page.goto(base+'/subscription');assert.ok(sub.id);mark('browser-subscription-create-branch');
 // Open the existing row editor through its name link.
 await page.getByRole('row').filter({hasText:'E2E Subscription'}).locator('.ant-dropdown-trigger').click();await page.getByText('编辑',{exact:true}).click();await page.getByRole('button',{name:'准备已保存的订阅'}).click();await until(async()=>((await api('/subscriptions')).data[0].worktree_id));await page.locator('.ant-modal:visible').getByRole('button',{name:/取.*消/}).click();
 await page.getByRole('row').filter({hasText:'E2E Subscription'}).getByText('运行',{exact:true}).click();await confirm();await until(async()=>((await api('/subscriptions')).data[0].last_sync_state==='SUCCESS'));mark('browser-prepare-sync-discovery');
 await page.goto(base+`/repository-workspace?id=${repo.id}`);await page.getByRole('tab',{name:/Worktrees/}).click();await page.getByRole('cell',{name:'branch: main',exact:true}).waitFor();mark('browser-worktree-view');
 async function variable(name,value,secret=false){await page.getByRole('button',{name:'添加变量',exact:true}).last().click();const dialog=page.locator('.ant-modal:visible');await dialog.getByLabel('变量名',{exact:true}).fill(name);if(secret)await dialog.getByLabel('Secret',{exact:true}).setChecked(true);await dialog.getByLabel(secret?'新 Secret 值':'值（允许空字符串）',{exact:true}).fill(value);await confirm();}
 await page.goto(base+'/env');await variable('GLOBAL_VALUE','global');await variable('SECRET_ENV','ENV_SECRET_E2E',true);mark('browser-global-create');
 await page.getByRole('tab',{name:'Repository',exact:true}).click();console.log('ENV_REPOSITORIES',JSON.stringify(await api('/scoped-env/repositories')));await choose('Repository','E2E Repo (0 Profiles)');await page.getByRole('button',{name:'创建 Profile'}).click();await page.getByLabel('Profile 名称',{exact:true}).fill('E2E Profile');await confirm();await page.getByRole('button',{name:'设为 Default'}).click();await page.getByRole('button',{name:'变量',exact:true}).click();await variable('PROFILE_VALUE','profile');mark('browser-profile-create-default');
 const tasks=(await api('/tasks')).data.data;assert.equal(tasks.length,3);mark('task-domain-discovery-three-languages');
 const checked=async(url,method='GET',body)=>{const r=await api(url,method,body);assert.ok([200,202].includes(r.code),url+': '+JSON.stringify(r));return r.data;};
 async function operation(url,body={},method='POST'){const requested=await checked(url,method,body);let op;await until(async()=>{op=await checked('/runtime/operations/'+requested.id);return !['QUEUED','RUNNING'].includes(op.status);});assert.equal(op.status,'SUCCESS',JSON.stringify(op));return op;}
 await operation('/runtime/python/provider/setup');await operation('/runtime/python/installations',{version:'3.13.15'});
 const pyRuntime=(await checked('/runtime/python/installations'))[0];
 const pyEnv=await checked('/runtime/python/environments','POST',{name:'Task Python Environment',runtime_id:pyRuntime.id,requirements:['ql-phase7-root==1.0.0']});await operation(`/runtime/python/environments/${pyEnv.id}/build`,{expected_version:pyEnv.version});
 await operation('/runtime/node/catalog');await operation('/runtime/node/installations',{version:require('./managed-node/result.json').runtime.version});const nodeRuntime=(await checked('/runtime/node/installations'))[0];await operation('/runtime/node/toolchains',{runtime_id:nodeRuntime.id,manager_type:'NPM'});const tool=(await checked('/runtime/node/toolchains'))[0];
 const nodeEnv=await checked('/runtime/node/environments','POST',{name:'Task Node Environment',runtime_id:nodeRuntime.id,toolchain_id:tool.id,dependencies:[{name:'ql-phase8-foo',specifier:'1.0.0',type:'DEPENDENCY'}],install_scripts_policy:'IGNORE'});await operation(`/runtime/node/environments/${nodeEnv.id}/build`,{expected_version:nodeEnv.version});mark('real-python-venv-and-node-dependency-environments');
 const dialog=()=>page.locator('.ant-modal:visible').filter({has:page.locator('.ant-modal-title').filter({hasText:/^(Task:|Create Task)/})});
 async function edit(task){await page.goto(base+'/tasks');await page.getByRole('button',{name:task.name,exact:true}).click();await dialog().waitFor();}
 async function save(){const response=page.waitForResponse(r=>/\/api\/tasks(?:\/\d+)?$/.test(new URL(r.url()).pathname)&&['POST','PUT'].includes(r.request().method()));await dialog().getByRole('button',{name:'Save Task',exact:true}).click();const r=await(await response).json();assert.equal(r.code,200,JSON.stringify(r));return r.data;}
 for(const task of tasks){await edit(task);await dialog().getByRole('tab',{name:'Source',exact:true}).click();assert.equal(await dialog().getByLabel('Worktree',{exact:true}).isDisabled(),true);await dialog().getByRole('tab',{name:'Runtime',exact:true}).click();if(task.resources.source.language!=='SHELL'){const isPy=task.resources.source.language==='PYTHON';await dialog().getByLabel(isPy?'Python Environment':'Node Environment',{exact:true}).locator('xpath=ancestor::div[contains(@class,"ant-select-selector")]').click();await page.locator('.ant-select-dropdown:visible').getByText(new RegExp(isPy?'Task Python Environment':'Task Node Environment')).click();}
   await dialog().getByRole('tab',{name:'Execution Settings',exact:true}).click();await dialog().getByLabel('Maximum attempts',{exact:true}).fill('3');await dialog().getByLabel('Timeout seconds (empty = platform default)',{exact:true}).fill('120');await choose('Notification','FAILURE',dialog());await save();await dialog().getByRole('button',{name:'Validate Task',exact:true}).click();await dialog().getByRole('tab',{name:'Resource Preview',exact:true}).click();await dialog().getByText('READY',{exact:true}).waitFor();await dialog().getByRole('button',{name:'Close',exact:true}).last().click();}
 mark('browser-discovered-task-runtime-settings-validation');
 // Manual source selection does not require discovery ownership.
 await page.getByRole('button',{name:'Create Task',exact:true}).click();await dialog().getByLabel('Name',{exact:true}).fill('Manual Python Task');await dialog().getByRole('tab',{name:'Source',exact:true}).click();await dialog().getByLabel('Worktree',{exact:true}).locator('xpath=ancestor::div[contains(@class,"ant-select-selector")]').click();await page.locator('.ant-select-dropdown:visible .ant-select-item-option-content').first().click();await choose('Entrypoint','job.py',dialog());await choose('Working directory','ENTRYPOINT_DIR',dialog());await dialog().getByRole('tab',{name:'Runtime',exact:true}).click();await dialog().getByLabel('Python Environment',{exact:true}).locator('xpath=ancestor::div[contains(@class,"ant-select-selector")]').click();await page.locator('.ant-select-dropdown:visible .ant-select-item-option-content').filter({hasText:'Task Python Environment'}).click();await dialog().getByRole('tab',{name:'Schedule',exact:true}).click();await dialog().getByRole('textbox',{name:'Schedule',exact:true}).fill('0 0 1 1 *');const manual=await save();assert.equal(manual.origin,'MANUAL');assert.equal(manual.subscription_id,null);await dialog().getByRole('button',{name:'Close',exact:true}).last().click();mark('browser-manual-worktree-entrypoint-create');
 // Browser acceptance for definition-only policies and rejected resource combinations.
 await dialog().waitFor({state:'hidden'});await edit(manual);
 await dialog().getByLabel('Arguments — JSON array',{exact:true}).fill('["--account","literal $TOKEN"]');
 await dialog().getByRole('tab',{name:'Execution Settings',exact:true}).click();await choose('Concurrency','QUEUE',dialog());
 await dialog().getByRole('tab',{name:'Runtime',exact:true}).click();await choose('Python Environment','Inherit — Subscription / Repository Default',dialog());
 const unbound=await save();assert.equal(unbound.resources.readiness.status,'CONFIGURATION_REQUIRED');assert.deepEqual(unbound.arguments,['--account','literal $TOKEN']);assert.equal(unbound.resources.settings.concurrency,'QUEUE');
 await dialog().getByLabel('Python Environment',{exact:true}).locator('xpath=ancestor::div[contains(@class,"ant-select-selector")]').click();assert.equal(await page.locator('.ant-select-dropdown:visible').getByText('Task Node Environment',{exact:true}).count(),0);await page.keyboard.press('Escape');
 const badRuntime=await api(`/tasks/${manual.id}`,'PUT',{name:manual.name,expected_version:unbound.version,source:Object.fromEntries(['type','worktree_id','relative_entrypoint','language','cwd_mode','cwd_relative_path'].map(key=>[key,unbound.source[key]])),runtime:{kind:'NODE',node_environment_id:nodeEnv.id}});assert.equal(badRuntime.code,400);assert.equal(badRuntime.error_code,'TASK_RUNTIME_KIND_MISMATCH');
 await dialog().getByLabel('Python Environment',{exact:true}).locator('xpath=ancestor::div[contains(@class,"ant-select-selector")]').click();await page.locator('.ant-select-dropdown:visible .ant-select-item-option-content').filter({hasText:'Task Python Environment'}).click();
 await dialog().getByRole('tab',{name:'Source',exact:true}).click();assert.equal(await dialog().getByLabel('Language',{exact:true}).inputValue(),'PYTHON');await choose('Working directory','CUSTOM_RELATIVE',dialog());await dialog().getByLabel('Relative working directory',{exact:true}).fill('../outside');
 const rejected=page.waitForResponse(r=>new URL(r.url()).pathname===`/api/tasks/${manual.id}`&&r.request().method()==='PUT');await dialog().getByRole('button',{name:'Save Task',exact:true}).click();const invalid=await(await rejected).json();assert.equal(invalid.code,400);assert.match(JSON.stringify(invalid),/PATH|SOURCE/);
 await choose('Working directory','ENTRYPOINT_DIR',dialog());await save();await dialog().getByRole('button',{name:'Close',exact:true}).last().click();mark('browser-arguments-concurrency-and-negative-resource-gates');

 for(const task of tasks){await page.goto(base+`/env?task=${task.id}`);await variable('TASK_VALUE','task');}
 await page.goto(base+'/config');await page.getByRole('button',{name:'创建 Config Asset',exact:true}).click();let child=page.locator('.ant-modal:visible').last();await child.getByLabel('Name',{exact:true}).fill('Task Config');await child.getByLabel('Content (UTF-8 TEXT, ≤ 1 MiB)',{exact:true}).fill('TASK_CONFIG');await confirm();
 for(const task of tasks){await edit(task);await dialog().getByRole('tab',{name:'Config',exact:true}).click();await page.getByRole('button',{name:'添加 Config Binding',exact:true}).click();child=page.locator('.ant-modal:visible').last();await choose('Config Asset','Task Config',child);await child.getByLabel('Target Path',{exact:true}).fill('config.txt');await child.getByRole('button',{name:/确.*定/}).click();await until(async()=> (await page.locator('.ant-modal:visible').count())===1);await dialog().getByRole('tab',{name:'Hooks',exact:true}).click();await page.getByRole('button',{name:'添加 BEFORE Hook',exact:true}).click();child=page.getByRole('dialog',{name:'Task Hook',exact:true});await child.getByLabel('Hook 名称',{exact:true}).fill('Before Task');await child.getByLabel('Command',{exact:true}).fill('token=generated-private-; token=${token}e2e; printf \'{"environment":{"set":{"HOOK_TOKEN":"%s"},"secret":["HOOK_TOKEN"]}}\' "$token" > "$PLATFORM_HOOK_OUTPUT"; echo PHASE10_BEFORE; echo "$token"');await child.getByRole('button',{name:/确.*定/}).click();await until(async()=> (await page.locator('.ant-modal:visible').count())===1);await dialog().getByRole('button',{name:'Validate Task',exact:true}).click();await dialog().getByRole('button',{name:'Close',exact:true}).last().click();}
 mark('browser-task-env-config-hooks');
 // Inheritance/override/reset through the actual runtime-default controls.
 const pyTask=tasks.find(x=>x.resources.source.language==='PYTHON');await edit(pyTask);await dialog().getByRole('tab',{name:'Runtime',exact:true}).click();await page.getByRole('combobox',{name:'Repository Runtime Default',exact:true}).locator('xpath=ancestor::div[contains(@class,"ant-select-selector")]').click();await page.locator('.ant-select-dropdown:visible').getByText('Task Python Environment',{exact:true}).click();await page.getByRole('button',{name:'Save Repository Default',exact:true}).click();await until(async()=> (await checked(`/repositories/${repo.id}/runtime-defaults`)).length===1);await choose('Python Environment','Inherit — Subscription / Repository Default',dialog());await save();assert.equal((await checked(`/tasks/${pyTask.id}/resources`)).runtime.selected_by,'REPOSITORY');
 await page.getByRole('combobox',{name:'Subscription Runtime Default',exact:true}).locator('xpath=ancestor::div[contains(@class,"ant-select-selector")]').click();await page.locator('.ant-select-dropdown:visible').getByText('Task Python Environment',{exact:true}).click();await page.getByRole('button',{name:'Save Subscription Default',exact:true}).click();await until(async()=> (await checked(`/tasks/${pyTask.id}/resources`)).runtime.selected_by==='SUBSCRIPTION');await dialog().getByLabel('Python Environment',{exact:true}).locator('xpath=ancestor::div[contains(@class,"ant-select-selector")]').click();await page.keyboard.press('ArrowDown');await page.keyboard.press('Enter');await save();assert.equal((await checked(`/tasks/${pyTask.id}/resources`)).runtime.selected_by,'TASK');await choose('Python Environment','Inherit — Subscription / Repository Default',dialog());await save();assert.equal((await checked(`/tasks/${pyTask.id}/resources`)).runtime.selected_by,'SUBSCRIPTION');await page.screenshot({path:path.join(__dirname,'browser-task-runtime.png'),fullPage:true});await dialog().getByRole('button',{name:'Close',exact:true}).last().click();mark('browser-runtime-default-inherit-override-reset');
 const row=page.getByRole('row').filter({has:page.getByRole('button',{name:pyTask.name,exact:true})});await row.getByRole('button',{name:'Clone',exact:true}).click();await dialog().waitFor();await dialog().getByRole('button',{name:'Close',exact:true}).last().click();const cloned=(await checked('/tasks')).data.find(t=>t.name===pyTask.name+' copy');assert.equal(cloned.origin,'MANUAL');assert.equal(cloned.resources.runtime.selected_by,'TASK');const enabledRow=page.getByRole('row').filter({has:page.getByRole('button',{name:cloned.name,exact:true})});await enabledRow.getByRole('switch').click();await until(async()=> (await checked(`/tasks/${cloned.id}`)).enabled);await until(async()=>await enabledRow.getByRole('switch').getAttribute('aria-checked')==='true');await enabledRow.getByRole('switch').click();await until(async()=> !(await checked(`/tasks/${cloned.id}`)).enabled);mark('browser-clone-disable-enable');
 await page.goto(base+'/runtime-python');await page.getByRole('tab',{name:'Environments',exact:true}).click();await page.getByRole('button',{name:'Task Python Environment',exact:true}).click();await page.getByText(/^Used by Tasks:/).waitFor();assert.equal(await page.getByRole('button',{name:'删除环境',exact:true}).isDisabled(),true);const deletion=await api(`/runtime/python/environments/${pyEnv.id}`,'DELETE',{expected_version:(await checked(`/runtime/python/environments/${pyEnv.id}`)).version});assert.equal(deletion.code,409);assert.match(JSON.stringify(deletion),/TASK_REFERENCED/);await page.screenshot({path:path.join(__dirname,'browser-used-by-tasks.png'),fullPage:true});mark('browser-environment-reference-protection');
 for(const task of [...tasks,cloned]){
   await page.goto(base+'/tasks');const taskRow=page.getByRole('row').filter({has:page.getByRole('button',{name:task.name,exact:true})});
   const submitted=page.waitForResponse(r=>new URL(r.url()).pathname===`/api/tasks/${task.id}/run`&&r.request().method()==='POST');await taskRow.getByRole('button',{name:'Run',exact:true}).click();const run=(await(await submitted).json()).data;let final;
   await until(async()=>{final=await checked(`/task-runs/${run.id}`);return !['QUEUED','RESOLVING','RUNNING'].includes(final.status);});assert.equal(final.status,'SUCCESS',JSON.stringify(final));
   const log=(await checked(`/task-runs/${run.id}/log`)).content;assert.ok(log.includes('global:profile:task'));assert.ok(log.includes('PHASE10_BEFORE'));assert.ok(log.includes('TASK_CONFIG'));assert.ok(log.includes('********'));
   if(task.resources.source.language==='PYTHON'){assert.ok(log.includes('MANAGED_PYTHON:'));assert.ok(log.includes('/venv/bin/python'));}
   if(task.resources.source.language==='JAVASCRIPT'){assert.ok(log.includes('MANAGED_NODE:'));assert.ok(log.includes('ql-phase8-foo@1.0.0'));}
   await taskRow.getByRole('button',{name:'Log',exact:true}).click();await page.getByRole('dialog',{name:'Run log',exact:true}).getByText(/PHASE10_BEFORE/).waitFor();await page.getByRole('dialog',{name:'Run log',exact:true}).getByRole('button',{name:'Close',exact:true}).click();
 }mark('browser-managed-python-node-shell-and-manual-clone-runs');
 const shellTask=tasks.find(t=>t.resources.source.language==='SHELL');const slow=await checked(`/tasks/${shellTask.id}/clone`,'POST',{name:'Cancel Run Fixture'});const slowDetail=await checked(`/tasks/${slow.id}`);
 await checked(`/tasks/${slow.id}`,'PUT',{name:slowDetail.name,arguments:['--sleep'],expected_version:slowDetail.version,source:Object.fromEntries(['type','worktree_id','relative_entrypoint','language','cwd_mode','cwd_relative_path'].map(key=>[key,slowDetail.source[key]])),runtime:{kind:'SHELL'},settings:{concurrency:'QUEUE',max_attempts:1}});
 await page.goto(base+'/tasks');const slowRow=page.getByRole('row').filter({has:page.getByRole('button',{name:'Cancel Run Fixture',exact:true})});await slowRow.getByRole('button',{name:'Run',exact:true}).click();let cancelRun;await until(async()=>{cancelRun=(await checked(`/tasks/${slow.id}/runs`))[0];return cancelRun?.status==='RUNNING';});
 await slowRow.getByRole('button',{name:'Runs',exact:true}).click();const runDialog=page.getByRole('dialog',{name:'Task runs',exact:true});await runDialog.getByRole('button',{name:'Cancel run',exact:true}).click();await until(async()=> (await checked(`/task-runs/${cancelRun.id}`)).status==='CANCELLED');await runDialog.getByRole('button',{name:'Refresh runs',exact:true}).click();await runDialog.getByText('CANCELLED',{exact:true}).first().waitFor();await page.screenshot({path:path.join(__dirname,'browser-task-runs.png'),fullPage:true});await runDialog.getByRole('button',{name:'Close',exact:true}).click();mark('browser-run-list-cancel-and-result');

 await stop();await start();await page.evaluate(()=>localStorage.removeItem('token'));await page.goto(base+'/login');await login();for(const task of [...tasks,manual,cloned])assert.equal((await checked(`/tasks/${task.id}/validate`,'POST')).readiness.status,'READY');mark('restart-validate-all-task-resources');
 const {Sequelize,QueryTypes}=require('sequelize');const db=new Sequelize({dialect:'sqlite',storage:path.join(tmp,'data/db/database.sqlite'),logging:false});assert.deepEqual(await db.query('PRAGMA foreign_key_check',{type:QueryTypes.SELECT}),[]);assert.equal((await db.query('SELECT platform_schema_version FROM PlatformMetadata',{type:QueryTypes.SELECT}))[0].platform_schema_version,7);await db.close();await delay(300);assert.deepEqual(leaks,[]);evidence.response_payloads_inspected=inspected.length;evidence.websocket_frames_inspected=websocketFrames;evidence.status='PASS';evidence.runtime_execution_activation='RUNNER_V2';mark('fresh-v7-restart-fk-secret-audit');
})().catch(async error=>{evidence.status='FAIL';evidence.error=error.stack;console.error(error);if(page)try{await page.screenshot({path:path.join(__dirname,'browser-failure.png'),fullPage:true});fs.writeFileSync(path.join(__dirname,'browser-failure.txt'),await page.locator('body').innerText());}catch{}process.exitCode=1;}).finally(async()=>{if(browser)await browser.close();await stop();if(packageIndex)await packageIndex.close();if(nodeRegistry)await nodeRegistry.close();for(const c of connections)c.end();if(ssh)ssh.close();fs.writeFileSync(path.join(__dirname,'platform-e2e.json'),JSON.stringify(evidence,null,2));fs.writeFileSync(path.join(__dirname,'platform-e2e-backend.log'),output);fs.rmSync(tmp,{recursive:true,force:true});});
