const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs/promises'),path=require('node:path'),{fork,execFileSync}=require('node:child_process'),{registry}=require('./registry.cjs'),{attach}=require('./managed-helper.cjs');
const source=require('../../diagnostics/phase8/managed-node/result.json');
async function until(read,predicate,ms=15000){const deadline=Date.now()+ms;while(Date.now()<deadline){const value=await read();if(predicate(value))return value;await new Promise(r=>setTimeout(r,80));}throw Error('Condition timeout');}
async function childStopped(pid){await until(async()=>{try{return execFileSync('/bin/ps',['-o','stat=','-p',String(pid)],{encoding:'utf8'}).trim();}catch{return '';}},s=>!s||s.startsWith('Z'));}
test('Node leases: parallel environments, shared provider independence, cancel/timeout/crash with complete process-group recovery',async t=>{
 const reg=await registry();t.after(()=>reg.close());const h=await attach(source.root,reg.url);t.after(()=>h.close());const s=h.service,ops=h.operations,r=(await s.runtimes()).find(x=>x.state==='READY'),tool=(await s.toolchains()).find(x=>x.manager_type==='PNPM'&&x.state==='READY');
 const created=[],results=[];const deps=name=>[{name,specifier:'1.0.0',type:'DEPENDENCY'}];
 async function create(name,slow=true){const e=await s.definition({name,runtime_id:r.id,toolchain_id:tool.id,dependencies:deps(slow?'ql-phase8-slow':'ql-phase8-foo')});created.push(e.id);return e;}
 async function start(env,timeout=120){env=await s.environment(env.id);return ops.request('NODE_ENV_BUILD',{node:{environment_id:env.id,expected_version:env.version},timeout_seconds:timeout});}
 async function ready(op){const file=await ops.paths.log(op.id);const log=await until(()=>fs.readFile(file,'utf8').catch(()=>''),x=>x.includes('PHASE8_SLOW_READY'));return Number(log.match(/PHASE8_CHILD_PID=(\d+)/)[1]);}
 const a=await create('phase8-slow-a'),b=await create('phase8-slow-b'),c=await create('phase8-limit-c');const opA=await start(a),pidA=await ready(opA),opB=await start(b),pidB=await ready(opB);
 assert.equal((await ops.operation(opA.id)).status,'RUNNING');assert.equal((await ops.operation(opB.id)).status,'RUNNING');await assert.rejects(start(c),/NODE_BUILD_CONCURRENCY_LIMIT/);
 for(const type of ['NODE_ENV_BUILD','NODE_ENV_DELETE','NODE_ENV_RESOLVE'])await assert.rejects(ops.request(type,{node:{environment_id:a.id,expected_version:(await s.environment(a.id)).version}}),/RUNTIME_BUSY/);
 await assert.rejects(ops.request('NODE_RUNTIME_REMOVE',{node:{runtime_id:r.id}}),/RUNTIME_BUSY/);await assert.rejects(ops.request('NODE_PACKAGE_MANAGER_REMOVE',{node:{toolchain_id:tool.id}}),/RUNTIME_BUSY/);
 // Controlled Python provider fixture exercises the same executor while real Node builds run.
 ops.provider.setup=async ctx=>{await ctx.stage('PYTHON_FIXTURE');await ctx.command.run('/bin/sh',['-c','sleep 1'],ctx.directory,ctx.environment);return {revision:ops.provider.revision,release:ops.provider.release};};ops.provider.catalog=async()=>['3.13.15'];
 const python=await ops.request((await ops.getProvider()).state==='READY'?'PROVIDER_UPDATE':'PROVIDER_INSTALL');assert.equal((await ops.wait(python.id)).status,'SUCCESS');assert.equal((await ops.operation(opA.id)).status,'RUNNING');
 await ops.cancel(opA.id);assert.equal((await ops.wait(opA.id)).status,'CANCELLED');await childStopped(pidA);await ops.cancel(opB.id);assert.equal((await ops.wait(opB.id)).status,'CANCELLED');await childStopped(pidB);
 for(const e of [a,b]){const builds=await s.builds(e.id);assert.equal(builds[0].state,'CANCELLED');await assert.rejects(fs.stat(await s.paths.target('build',builds[0].id,e.id)),{code:'ENOENT'});}
 const timed=await start(c,3),pidC=await ready(timed);const timeout=await ops.wait(timed.id);assert.equal(timeout.error_code,'RUNTIME_TIMEOUT');assert.equal(timeout.exit_code,124);await childStopped(pidC);
 const keep=await create('phase8-crash-keep',false),initial=await start(keep);assert.equal((await ops.wait(initial.id)).status,'SUCCESS');let current=await s.environment(keep.id);const before=current.current_build_id;await s.definition({name:current.name,runtime_id:r.id,toolchain_id:tool.id,dependencies:deps('ql-phase8-slow'),expected_version:current.version},keep.id);
 const worker=fork(path.join(__dirname,'crash-worker.cjs'),[source.root,reg.url,String(keep.id)],{stdio:['ignore','pipe','pipe','ipc'],env:{PATH:process.env.PATH}});t.after(()=>{if(worker.exitCode===null)worker.kill('SIGKILL');});const message=await new Promise((resolve,reject)=>{worker.once('message',resolve);worker.once('error',reject);worker.stderr.on('data',x=>console.log(String(x)));});const crashOp=await ops.operation(message.operation_id),pid=await ready(crashOp);worker.kill('SIGKILL');await new Promise(r=>worker.once('exit',r));await childStopped(pid);
 await until(async()=>{await ops.recover();return ops.operation(crashOp.id);},x=>x.status==='INTERRUPTED');assert.equal((await s.environment(keep.id)).current_build_id,before);assert.equal((await s.build(Number(crashOp.metadata.build_id),keep.id)).state,'INTERRUPTED');
 // A fresh service instance resolves retained resources after restart.
 const reopened=await attach(source.root,reg.url);const Resolver=reopened.load('back/services/nodeEnvironmentResolver.ts').default,pin=await new Resolver(reopened.service).resolve(keep.id);assert.equal(pin.snapshot.build_id,before);await pin.lease.release();await reopened.close();
 for(const id of created){const e=await s.environment(id),op=await ops.request('NODE_ENV_DELETE',{node:{environment_id:id,expected_version:e.version}});const done=await ops.wait(op.id);assert.equal(done.status,'SUCCESS');}
 await fs.writeFile('diagnostics/phase8/lifecycle-result.json',JSON.stringify({status:'PASS',parallel_environments:true,python_provider_parallel:true,cancelled_pids:[pidA,pidB],timeout_pid:pidC,crash_pid:pid,current_preserved:before,all_children_stopped:true,restart_resolver:true},null,2)+'\n');
});
