const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs/promises'),path=require('node:path'),{registry}=require('./registry.cjs'),{attach,treeDigest}=require('./managed-helper.cjs');
const source=require('../../diagnostics/phase8/managed-node/result.json');
test('real managed Node + pnpm/npm, local registry, immutable snapshots, frozen rebuild, refs, leases and scripts',async t=>{
 assert.equal(source.status,'PASS','Provision official managed Node first');const registryFixture=await registry();t.after(()=>registryFixture.close());
 const h=await attach(source.root,registryFixture.url);const service=h.service,operations=h.operations,Resolver=h.load('back/services/nodeEnvironmentResolver.ts').default;
 const runtime=(await service.runtimes()).find(x=>x.state==='READY'),tools=await service.toolchains(),pnpm=tools.find(x=>x.manager_type==='PNPM'&&x.state==='READY'),npm=tools.find(x=>x.manager_type==='NPM'&&x.state==='READY');assert.ok(runtime&&pnpm&&npm);
 const runtimeRoot=await service.paths.assertOwned('runtime',runtime.id),runtimeHash=await treeDigest(runtimeRoot),toolHash=await treeDigest(await service.paths.assertOwned('toolchain',pnpm.id));
 const created=[];const results=[];async function run(type,input,status='SUCCESS'){const op=await operations.request(type,{node:input,timeout_seconds:120}),done=await operations.wait(op.id);results.push({type,status:done.status,error:done.error_code});if(done.status!==status)console.log(await fs.readFile(await operations.paths.log(op.id),'utf8'));assert.equal(done.status,status);return done;}
 t.after(async()=>{try{for(const id of created){try{const env=await service.environment(id);await run('NODE_ENV_DELETE',{environment_id:id,expected_version:env.version});}catch(e){if(!/NOT_FOUND/.test(String(e)))throw e;}}for(const tool of await service.toolchains())if(tool.version==='10.99.1')await run('NODE_PACKAGE_MANAGER_REMOVE',{toolchain_id:tool.id});}finally{await h.close();}});
 const dep=(name,specifier='1.0.0',type='DEPENDENCY')=>({name,specifier,type});
 async function create(name,tool=pnpm,dependencies=[dep('ql-phase8-foo'),dep('@phase8/scoped')],policy='ALLOW',production_only=false){const env=await service.definition({name,runtime_id:runtime.id,toolchain_id:tool.id,dependencies,install_scripts_policy:policy,production_only});created.push(env.id);return env;}
 async function build(env,type='NODE_ENV_BUILD'){env=await service.environment(env.id);await run(type,{environment_id:env.id,expected_version:env.version});env=await service.environment(env.id);return service.build(env.current_build_id,env.id);}
 const a=await create('phase8-a'),first=await build(a);assert.ok(first.resolved.some(x=>x.name==='ql-phase8-leaf'&&!x.direct));assert.ok(first.resolved.some(x=>x.name==='@phase8/scoped'&&x.direct));assert.match(first.lockfile,/lockfileVersion/);
 const firstRoot=await service.paths.assertOwned('build',first.id,a.id),firstHash=await treeDigest(firstRoot);
 await registryFixture.add('ql-phase8-leaf','1.1.0');const frozen=await build(a,'NODE_ENV_REBUILD');assert.equal(frozen.lock_hash,first.lock_hash);assert.equal(frozen.resolved_hash,first.resolved_hash);
 const resolved=await build(a,'NODE_ENV_RESOLVE');assert.ok(resolved.resolved.some(x=>x.name==='ql-phase8-leaf'&&x.version==='1.1.0'));
 let env=await service.environment(a.id);env=await service.definition({name:env.name,runtime_id:runtime.id,toolchain_id:pnpm.id,dependencies:[dep('ql-phase8-foo','2.0.0')],expected_version:env.version},env.id);const second=await build(env);
 const diff=await service.diff(a.id,first.id,second.id);assert.ok(diff.some(x=>x.name==='ql-phase8-foo'&&x.change==='CHANGED'));assert.ok(diff.some(x=>x.name==='ql-phase8-extra'&&x.change==='ADDED'));assert.equal(await treeDigest(firstRoot),firstHash);
 env=await service.environment(a.id);await run('NODE_ENV_PROMOTE',{environment_id:a.id,build_id:first.id,expected_version:env.version});assert.equal((await service.environment(a.id)).current_build_id,first.id);
 const pin=await new Resolver(service).resolve(a.id),pin2=await new Resolver(service).resolve(a.id);assert.equal(pin.snapshot.build_id,first.id);assert.ok(path.isAbsolute(pin.snapshot.node_executable));env=await service.environment(a.id);await assert.rejects(operations.request('NODE_ENV_DELETE',{node:{environment_id:a.id,expected_version:env.version}}),/RUNTIME_BUSY/);await pin.lease.release();await pin2.lease.release();
 await assert.rejects(operations.request('NODE_RUNTIME_REMOVE',{node:{runtime_id:runtime.id}}),/RUNTIME_REFERENCED/);await assert.rejects(operations.request('NODE_PACKAGE_MANAGER_REMOVE',{node:{toolchain_id:pnpm.id}}),/NODE_TOOLCHAIN_REFERENCED/);
 const b=await create('phase8-b');const bbuild=await build(b),broot=await service.paths.assertOwned('build',bbuild.id,b.id);assert.notEqual(broot,firstRoot);const y1=await fs.readFile(path.join(firstRoot,'pnpm-workspace.yaml'),'utf8'),y2=await fs.readFile(path.join(broot,'pnpm-workspace.yaml'),'utf8');assert.equal(y1,y2);
 const saved={secret:process.env.PHASE8_BACKEND_SECRET,options:process.env.NODE_OPTIONS,proxy:process.env.HTTP_PROXY};process.env.PHASE8_BACKEND_SECRET='phase8-must-not-inherit';process.env.NODE_OPTIONS='--throw-deprecation';process.env.HTTP_PROXY='http://secret:credential@127.0.0.1:1';
 try{for(const tool of [pnpm,npm])for(const policy of ['ALLOW','IGNORE']){const e=await create('phase8-'+tool.manager_type+'-'+policy,tool,[dep('ql-phase8-script'),dep('@phase8/scoped','1.0.0','DEV_DEPENDENCY')],policy,true),built=await build(e),root=await service.paths.assertOwned('build',built.id,e.id),marker=path.join(root,'node_modules/ql-phase8-script/postinstall-marker');if(policy==='ALLOW'){const text=JSON.parse(await fs.readFile(marker,'utf8'));assert.equal(text.secret,null);assert.equal(text.node_options,null);assert.equal(text.proxy,null);assert.equal(text.executable,path.join(runtimeRoot,'bin/node'));}else await assert.rejects(fs.stat(marker),{code:'ENOENT'});assert.ok(!built.resolved.some(x=>x.name==='@phase8/scoped'));await run('NODE_ENV_VERIFY',{environment_id:e.id,build_id:built.id,expected_version:(await service.environment(e.id)).version});if(tool===npm){assert.equal(JSON.parse(built.lockfile).lockfileVersion,3);await build(e,'NODE_ENV_REBUILD');}}}finally{for(const [key,val] of [['PHASE8_BACKEND_SECRET',saved.secret],['NODE_OPTIONS',saved.options],['HTTP_PROXY',saved.proxy]])if(val===undefined)delete process.env[key];else process.env[key]=val;}
 env=await service.environment(a.id);await service.definition({name:env.name,runtime_id:runtime.id,toolchain_id:pnpm.id,dependencies:[dep('ql-phase8-broken')],expected_version:env.version},env.id);await run('NODE_ENV_BUILD',{environment_id:a.id,expected_version:(await service.environment(a.id)).version},'FAILED');assert.equal((await service.environment(a.id)).current_build_id,first.id);assert.equal(await treeDigest(firstRoot),firstHash);
 for(const invalid of [dep('--global'),dep('x','file:../x'),dep('x','workspace:*'),dep('x','git+ssh://evil'),dep('x','https://evil/pkg.tgz'),dep('x','$(touch /tmp/a)'),dep('x','1.0.0\n--global'),dep('x','latest')])await assert.rejects(create('invalid-'+Math.random(),pnpm,[invalid]),/NODE_DEPENDENCY_INVALID/);
 await assert.rejects(create('duplicate',pnpm,[dep('x'),dep('x')]),/NODE_DEPENDENCY_INVALID/);
 await run('NODE_PACKAGE_MANAGER_INSTALL',{runtime_id:runtime.id,manager_type:'PNPM',version:'10.99.1'},'FAILED');
 const clone=await service.clone(b.id,'phase8-clone');created.push(clone.id);const cloned=await build(clone);assert.notEqual(cloned.id,bbuild.id);
 const lock=path.join(broot,'pnpm-lock.yaml'),originalLock=await fs.readFile(lock);await fs.appendFile(lock,'# tampered\n');await run('NODE_ENV_VERIFY',{environment_id:b.id,build_id:bbuild.id,expected_version:(await service.environment(b.id)).version},'FAILED');await assert.rejects(new Resolver(service).resolve(b.id));await fs.writeFile(lock,originalLock);await run('NODE_ENV_VERIFY',{environment_id:b.id,build_id:bbuild.id,expected_version:(await service.environment(b.id)).version});
 assert.equal(await treeDigest(runtimeRoot),runtimeHash);assert.equal(await treeDigest(await service.paths.assertOwned('toolchain',pnpm.id)),toolHash);
 for(const id of created){const e=await service.environment(id);await run('NODE_ENV_DELETE',{environment_id:id,expected_version:e.version});}assert.ok((await fs.readdir(await service.paths.directory('cache/node/pnpm-store/toolchain-'+pnpm.id))).length);
 await fs.writeFile('diagnostics/phase8/offline-result.json',JSON.stringify({status:'PASS',runtime:runtime.version,pnpm:pnpm.version,npm:npm.version,operations:results,registry_requests:registryFixture.requests.length,runtime_unchanged:true,toolchain_unchanged:true},null,2)+'\n');
});
