const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs/promises'),path=require('node:path'),os=require('node:os');
const {execFileSync}=require('node:child_process');
const sync=require('node:fs'),codeRoot=sync.mkdtempSync(path.join(sync.realpathSync(os.tmpdir()),'phase14-code-'));
sync.writeFileSync(path.join(codeRoot,'.env'),'JWT_SECRET=isolated-phase14-test\n',{mode:0o600});sync.symlinkSync(path.resolve('shell'),path.join(codeRoot,'shell'));sync.symlinkSync(path.resolve('static'),path.join(codeRoot,'static'));process.env.QL_DIR=codeRoot;process.on('exit',()=>sync.rmSync(codeRoot,{recursive:true,force:true}));
process.env.TS_NODE_PROJECT=path.resolve('back/tsconfig.json');require('ts-node/register/transpile-only');
const {BackupPaths}=require('../../back/services/backup/paths.ts');
const {BackupCoordinator}=require('../../back/services/backup/coordinator.ts');
const {RestoreService}=require('../../back/services/backup/restore.ts');
async function fixture(t){const root=await fs.mkdtemp(path.join(await fs.realpath(os.tmpdir()),'phase14-production-'));t.after(()=>fs.rm(root,{recursive:true,force:true}));const data=path.join(root,'A');await fs.mkdir(path.join(data,'db'),{recursive:true,mode:0o700});execFileSync(process.execPath,['static/build/backupCandidate.js'],{env:{...process.env,QL_DIR:codeRoot,QL_DATA_DIR:data},stdio:'pipe'});await fs.chmod(path.join(data,'db/database.sqlite'),0o600);return {root,data,paths:new BackupPaths(data)};}
test('production snapshot, encrypted transfer and offline restore to an absent different DATA_DIR',async t=>{
 const h=await fixture(t);await fs.writeFile(path.join(h.data,'user-data'),'UNIQUE_SUPER_SECRET_PHASE14',{mode:0o644});await fs.writeFile(path.join(h.data,'execute.sh'),'#!/bin/sh\nexit 0\n',{mode:0o755});await fs.symlink('user-data',path.join(h.data,'safe-link'));
 const backup=new BackupCoordinator(h.paths),id=await backup.create();assert.equal((await backup.list())[0].id,id);await backup.validate(id);
 const exported=await backup.export(id,Buffer.from('phase14-secret-passphrase'));const encrypted=await fs.readFile(await h.paths.bucket('exports',exported));assert.ok(!encrypted.includes('UNIQUE_SUPER_SECRET_PHASE14'));
 const target=new BackupPaths(path.join(h.root,'B'));await target.initialize();const other=new BackupCoordinator(target);
 await assert.rejects(other.import(await h.paths.bucket('exports',exported),Buffer.from('incorrect-passphrase')));
 const imported=await other.import(await h.paths.bucket('exports',exported),Buffer.from('phase14-secret-passphrase'));
 await fs.rm(h.data,{recursive:true});const restore=new RestoreService(target);await restore.stage(imported,'imports',true);assert.equal((await restore.status()).stage,'PENDING');await restore.apply();assert.equal((await restore.status()).stage,'COMPLETE');
 assert.equal(await fs.readFile(path.join(target.data,'user-data'),'utf8'),'UNIQUE_SUPER_SECRET_PHASE14');assert.equal((await fs.stat(path.join(target.data,'user-data'))).mode&0o777,0o644);assert.equal((await fs.stat(path.join(target.data,'execute.sh'))).mode&0o777,0o755);assert.equal(await fs.readlink(path.join(target.data,'safe-link')),'user-data');
 await restore.apply();assert.equal(await other.barrier.state(),null);
});
const {backupDatabase}=require('../../back/services/backup/sqlite.ts');
test('Git local-only refs, dirty, ignored and untracked worktree data survive source destruction',async t=>{
 const h=await fixture(t),bare=path.join(h.data,'git/example.test/repository-1.git'),wt=path.join(h.data,'worktrees/repository-1/wt-1');
 await fs.mkdir(path.dirname(bare),{recursive:true,mode:0o700});await fs.mkdir(path.dirname(wt),{recursive:true,mode:0o700});
 const git=(args)=>execFileSync('git',args,{env:{...process.env,GIT_AUTHOR_NAME:'Fixture',GIT_AUTHOR_EMAIL:'fixture@example.test',GIT_COMMITTER_NAME:'Fixture',GIT_COMMITTER_EMAIL:'fixture@example.test'},stdio:'pipe'}).toString().trim();
 git(['init','--bare',bare]);git(['--git-dir',bare,'worktree','add','--orphan','-b','local-only',wt]);
 await fs.writeFile(path.join(wt,'tracked'),'original');await fs.writeFile(path.join(wt,'.gitignore'),'ignored\n');git(['-C',wt,'add','.']);git(['-C',wt,'commit','-m','local only']);git(['-C',wt,'tag','local-tag']);const head=git(['-C',wt,'rev-parse','HEAD']);
 await fs.writeFile(path.join(wt,'tracked'),'dirty');await fs.writeFile(path.join(wt,'untracked'),'untracked');await fs.writeFile(path.join(wt,'ignored'),'must survive');
 const db=await backupDatabase(path.join(h.data,'db/database.sqlite'),true);await db.all("INSERT INTO Repositories(id,name,provider,remote_url,normalized_url,host,storage_state,storage_path,createdAt,updatedAt) VALUES(1,'fixture','generic','https://example.test/unavailable','https://example.test/unavailable','example.test','READY',?,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP)",[bare]);await db.all("INSERT INTO Worktrees(id,repository_id,name,ref_type,ref_name,branch,local_path,lifecycle_state,createdAt,updatedAt) VALUES(1,1,'fixture','branch','local-only','local-only',?,'READY',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP)",[wt]);await db.close();
 const backup=new BackupCoordinator(h.paths),id=await backup.create(),exported=await backup.export(id,Buffer.from('phase14-secret-passphrase'));
 const target=new BackupPaths(path.join(h.root,'different-root'));await target.initialize();const imported=await new BackupCoordinator(target).import(await h.paths.bucket('exports',exported),Buffer.from('phase14-secret-passphrase'));const originalRegistration=await fs.readFile(path.join(wt,'.git'));const originalAdmin=await fs.readFile(path.join(bare,'worktrees/wt-1/gitdir'));const repairCandidate=path.join(h.root,'repair-candidate');await fs.cp(h.data,repairCandidate,{recursive:true,verbatimSymlinks:true});await new(require('../../back/services/backup/git.ts').BackupRestoreGitRepairService)().verify(repairCandidate,true);assert.deepEqual(await fs.readFile(path.join(wt,'.git')),originalRegistration);assert.deepEqual(await fs.readFile(path.join(bare,'worktrees/wt-1/gitdir')),originalAdmin);await fs.rm(h.data,{recursive:true});
 const restore=new RestoreService(target);await restore.stage(imported,'imports',true);await restore.apply();const newWt=path.join(target.data,'worktrees/repository-1/wt-1');assert.equal(git(['-C',newWt,'rev-parse','HEAD']),head);assert.equal(git(['-C',newWt,'rev-parse','local-tag']),head);assert.equal(await fs.readFile(path.join(newWt,'tracked'),'utf8'),'dirty');assert.equal(await fs.readFile(path.join(newWt,'ignored'),'utf8'),'must survive');assert.match(git(['-C',newWt,'status','--porcelain']),/untracked/);
 const marker=path.join(h.root,'filter-executed');git(['--git-dir',path.join(target.data,'git/example.test/repository-1.git'),'config','filter.probe.clean','touch '+marker]);await assert.rejects(new BackupCoordinator(target).create(),/BACKUP_GIT_CONFIG_UNSUPPORTED/);await assert.rejects(fs.lstat(marker),{code:'ENOENT'});
});
for(const point of ['during-schema-migration','during-git-repair','after-candidate-validation','after-old-rename','after-candidate-publish','before-startup-validation','after-startup-validation'])test('restore SIGKILL recovery: '+point,async t=>{
 const h=await fixture(t);await fs.writeFile(path.join(h.data,'restored-value'),'from snapshot',{mode:0o600});const backup=new BackupCoordinator(h.paths),id=await backup.create();await fs.writeFile(path.join(h.data,'restored-value'),'pre-restore data',{mode:0o600});
 const restore=new RestoreService(h.paths);await restore.stage(id,'snapshots',true);
 const result=require('node:child_process').spawnSync(process.execPath,['tests/phase14/restore-worker.cjs',h.data,point],{env:process.env,encoding:'utf8'});assert.equal(result.signal,'SIGKILL',result.stderr);
 await restore.apply();assert.equal((await restore.status()).stage,'COMPLETE');assert.equal(await fs.readFile(path.join(h.data,'restored-value'),'utf8'),'from snapshot');
 const journal=await restore.journal();assert.equal(await fs.readFile(path.join(journal.old_root,'restored-value'),'utf8'),'pre-restore data');assert.ok(journal.safety_snapshot);await backup.validate(journal.safety_snapshot);
});
test('post-switch validation failure restores original directory and preserves failed candidate',async t=>{
 const h=await fixture(t);await fs.writeFile(path.join(h.data,'value'),'snapshot',{mode:0o600});const backup=new BackupCoordinator(h.paths),id=await backup.create();await fs.writeFile(path.join(h.data,'value'),'original',{mode:0o600});const restore=new RestoreService(h.paths,async point=>{if(point==='before-startup-validation')throw Error('injected');});await restore.stage(id,'snapshots',true);await assert.rejects(restore.apply(),/RESTORE_RECOVERY_REQUIRED/);assert.equal((await restore.status()).stage,'ROLLED_BACK');assert.equal(await fs.readFile(path.join(h.data,'value'),'utf8'),'original');await new RestoreService(h.paths).apply();assert.equal(await backup.barrier.state(),null);
});
test('snapshot and restore reject tampering, unsafe roots and substituted ownership',async t=>{
 const h=await fixture(t),backup=new BackupCoordinator(h.paths);await fs.writeFile(path.join(h.data,'value'),'original',{mode:0o600});const id=await backup.create(),snapshot=await h.paths.bucket('snapshots',id),file=path.join(snapshot,'data/value');
 await assert.rejects(backup.validate('../escape'),/BACKUP_ID_INVALID/);
 await fs.writeFile(file,'modified');await assert.rejects(backup.validate(id),/BACKUP_CHECKSUM_FAILED/);await fs.writeFile(file,'original');await fs.chmod(file,0o644);await assert.rejects(backup.validate(id));await fs.chmod(file,0o600);
 const manifestFile=path.join(snapshot,'manifest.json'),manifest=await fs.readFile(manifestFile);await fs.writeFile(manifestFile,'{}');await assert.rejects(backup.validate(id),/BACKUP_MANIFEST_INVALID/);await fs.writeFile(manifestFile,manifest);
 const database=path.join(snapshot,'data/db/database.sqlite'),bytes=await fs.readFile(database);await fs.writeFile(database,'invalid');await assert.rejects(backup.validate(id));await fs.writeFile(database,bytes);
 const outside=path.join(h.root,'outside');await fs.mkdir(outside,{mode:0o700});await fs.writeFile(path.join(outside,'preserve'),'keep');const moved=snapshot+'-moved';await fs.rename(snapshot,moved);await fs.symlink(outside,snapshot);await assert.rejects(h.paths.remove('snapshots',id));assert.equal(await fs.readFile(path.join(outside,'preserve'),'utf8'),'keep');await fs.unlink(snapshot);await fs.rename(moved,snapshot);
 const badRoot=path.join(h.root,'symlink-backups');await fs.symlink(h.paths.root,badRoot);await assert.rejects(new BackupPaths(h.data,badRoot).initialize());
 const restore=new RestoreService(h.paths);await restore.stage(id,'snapshots',true);const journalFile=path.join(h.paths.control,'restore-journal.json'),journal=await fs.readFile(journalFile);await fs.writeFile(journalFile,'{}');await assert.rejects(restore.apply(),/RESTORE_JOURNAL_INVALID/);await fs.writeFile(journalFile,journal);
 const value=JSON.parse(journal);value.journal.candidate=outside;value.checksum=require('node:crypto').createHash('sha256').update(JSON.stringify(value.journal)).digest('hex');await fs.writeFile(journalFile,JSON.stringify(value));await assert.rejects(restore.apply(),/RESTORE_JOURNAL_INVALID/);await fs.writeFile(journalFile,journal);await restore.cancel();
 await fs.symlink('/etc/passwd',path.join(h.data,'unsafe'));await assert.rejects(backup.create(),/BACKUP_SOURCE_UNSAFE_SYMLINK/);assert.equal(await backup.barrier.state(),null);await fs.unlink(path.join(h.data,'unsafe'));
 await fs.link(path.join(h.data,'value'),path.join(h.data,'hardlink'));await assert.rejects(backup.create(),/BACKUP_FILE_INVALID/);await fs.unlink(path.join(h.data,'hardlink'));
 execFileSync('mkfifo',[path.join(h.data,'fifo')]);await assert.rejects(backup.create(),/BACKUP_SOURCE_SPECIAL_FILE/);await fs.unlink(path.join(h.data,'fifo'));assert.equal((await backup.list()).length,1);
});
test('100,000 historical Runs and 100 MiB logs snapshot, validate and restore with sampled RSS',async t=>{
 const h=await fixture(t),db=await backupDatabase(path.join(h.data,'db/database.sqlite'),true);
 await db.all("WITH RECURSIVE n(x) AS (SELECT 1 UNION ALL SELECT x+1 FROM n WHERE x<100000) INSERT INTO TaskRuns(task_id,status,trigger_type,submitted_at,started_at,finished_at,log_identity,concurrency_policy,createdAt,updatedAt) SELECT NULL,'SUCCESS','API',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'scale-'||x,'ALLOW',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP FROM n");await db.close();
 await fs.mkdir(path.join(h.data,'log/task-runs'),{recursive:true,mode:0o700});const log=await fs.open(path.join(h.data,'log/task-runs/run-1.log'),'wx',0o600);const chunk=Buffer.alloc(64*1024,65);for(let i=0;i<1600;i++)await log.write(chunk);await log.sync();await log.close();
 const bare=path.join(h.data,'git/example.test/repository-1.git');await fs.mkdir(path.dirname(bare),{recursive:true,mode:0o700});execFileSync('git',['init','--bare',bare],{stdio:'pipe'});
 let input='commit refs/heads/main\ncommitter Fixture <fixture@example.test> 1700000000 +0000\ndata 5\nscale\n';for(let i=0;i<2000;i++)input+=`M 100644 inline file-${i}\ndata ${String(i).length}\n${i}\n`;input+='\ndone\n';execFileSync('git',['--git-dir',bare,'fast-import','--quiet'],{input,stdio:['pipe','pipe','pipe']});const write=await backupDatabase(path.join(h.data,'db/database.sqlite'),true);await write.all("INSERT INTO Repositories(id,name,provider,remote_url,normalized_url,host,storage_state,storage_path,createdAt,updatedAt) VALUES(1,'scale','generic','https://example.test/unavailable','https://example.test/unavailable','example.test','READY',?,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP)",[bare]);await write.close();
 const samples=[process.memoryUsage().rss],timer=setInterval(()=>samples.push(process.memoryUsage().rss),50),started=Date.now();t.after(()=>clearInterval(timer));const backup=new BackupCoordinator(h.paths),id=await backup.create();await backup.validate(id);const restore=new RestoreService(h.paths);await restore.stage(id,'snapshots',true);await restore.apply();const result=await backupDatabase(path.join(h.data,'db/database.sqlite'));assert.equal((await result.all('SELECT COUNT(*) n FROM TaskRuns'))[0].n,100000);await result.close();assert.equal((await fs.stat(path.join(h.data,'log/task-runs/run-1.log'))).size,100*1024*1024);clearInterval(timer);t.diagnostic(JSON.stringify({runs:100000,log_bytes:100*1024*1024,git_files:2000,elapsed_ms:Date.now()-started,rss_start:samples[0],rss_peak:Math.max(...samples),rss_end:process.memoryUsage().rss,samples:samples.length}));
});
test('production bootstrap makes SQLite private and unknown runtime data blocks exclusion',async t=>{
 const h=await fixture(t),file=path.join(h.data,'db/database.sqlite');await fs.chmod(file,0o644);await fs.chmod(h.data,0o755);await require('../../back/services/backup/bootstrap.ts').prepareOperationalDatabase(h.data);assert.equal((await fs.stat(file)).mode&0o777,0o600);
 await fs.mkdir(path.join(h.data,'runtime/user-unique'),{recursive:true,mode:0o700});await fs.writeFile(path.join(h.data,'runtime/user-unique/value'),'preserve');await assert.rejects(new BackupCoordinator(h.paths).create(),/BACKUP_RECOVERY_REQUIRED/);assert.equal(await fs.readFile(path.join(h.data,'runtime/user-unique/value'),'utf8'),'preserve');
});
test('future schema, candidate and quarantine substitution fail closed',async t=>{
 const h=await fixture(t),backup=new BackupCoordinator(h.paths),id=await backup.create();await fs.writeFile(path.join(h.data,'unique'),'original',{mode:0o600});
 const restore=new RestoreService(h.paths,async point=>{if(point==='after-candidate-validation')throw Error('pause before switch');});await restore.stage(id,'snapshots',true);await assert.rejects(restore.apply(),/pause before switch/);const journal=await restore.journal();await fs.rename(journal.candidate,journal.candidate+'-owned');await fs.mkdir(journal.candidate,{mode:0o700});await assert.rejects(new RestoreService(h.paths).apply(),/RESTORE_RECOVERY_REQUIRED/);assert.equal(await fs.readFile(path.join(h.data,'unique'),'utf8'),'original');await fs.rmdir(journal.candidate);await fs.rename(journal.candidate+'-owned',journal.candidate);
 await fs.mkdir(journal.old_root,{mode:0o700});await fs.writeFile(path.join(journal.old_root,'unknown'),'keep');await assert.rejects(new RestoreService(h.paths).apply(),/RESTORE_RECOVERY_REQUIRED/);assert.equal(await fs.readFile(path.join(journal.old_root,'unknown'),'utf8'),'keep');assert.equal(await fs.readFile(path.join(h.data,'unique'),'utf8'),'original');
 const db=await backupDatabase(path.join(h.data,'db/database.sqlite'),true);await db.all('PRAGMA ignore_check_constraints=ON');await db.all('UPDATE PlatformMetadata SET platform_schema_version=99');await db.close();await assert.rejects(backup.validator.domains(h.data),/RESTORE_BACKUP_TOO_NEW/);
});
test('cancel is durable before marker cleanup; logger import never creates DATA_DIR',async t=>{
 const h=await fixture(t),backup=new BackupCoordinator(h.paths),id=await backup.create(),restore=new RestoreService(h.paths);await restore.stage(id,'snapshots',true);await restore.cancel();assert.equal((await restore.status()).stage,'CANCELLED');assert.equal(await backup.barrier.state(),null);await restore.apply();assert.equal((await restore.status()).stage,'CANCELLED');
 const absent=path.join(h.root,'never-created');execFileSync(process.execPath,['-e',"require('./static/build/loaders/logger.js');setImmediate(()=>process.exit(0));"],{env:{...process.env,QL_DATA_DIR:absent},stdio:'pipe'});await assert.rejects(fs.lstat(absent),{code:'ENOENT'});
});
test('real application refuses malformed restore journal before creating a DATA_DIR',async t=>{
 const root=await fs.mkdtemp(path.join(await fs.realpath(os.tmpdir()),'phase14-startup-'));t.after(()=>fs.rm(root,{recursive:true,force:true}));const paths=new BackupPaths(path.join(root,'absent'));await paths.initialize();await fs.writeFile(path.join(paths.control,'restore-journal.json'),'{}',{mode:0o600});
 const result=require('node:child_process').spawnSync(process.execPath,['static/build/app.js'],{env:{...process.env,QL_DATA_DIR:paths.data},encoding:'utf8',timeout:15000});assert.equal(result.status,1);assert.match(result.stdout+result.stderr,/RESTORE_JOURNAL_INVALID/);await assert.rejects(fs.lstat(paths.data),{code:'ENOENT'});
});
test('offline restore accepts an explicitly created empty destination without inventing a safety snapshot',async t=>{
 const h=await fixture(t),backup=new BackupCoordinator(h.paths),id=await backup.create(),target=new BackupPaths(path.join(h.root,'empty-B'),h.paths.root);await fs.mkdir(target.data,{mode:0o700});const restore=new RestoreService(target);await restore.stage(id,'snapshots',true);await restore.apply();const journal=await restore.journal();assert.equal(journal.stage,'COMPLETE');assert.equal(journal.old_empty,true);assert.equal(journal.safety_snapshot,undefined);assert.deepEqual(await fs.readdir(journal.old_root),[]);assert.ok(await fs.stat(path.join(target.data,'db/database.sqlite')));
});
test('domain validation rejects damaged Config revisions and Git objects before READY',async t=>{
 const h=await fixture(t),db=await backupDatabase(path.join(h.data,'db/database.sqlite'),true),content='UNIQUE_SUPER_SECRET_CONFIG_REVISION';
 await db.all("INSERT INTO ConfigAssets(id,name,createdAt,updatedAt) VALUES(1,'fixture',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP)");
 await db.all("INSERT INTO ConfigAssetRevisions(id,asset_id,revision_number,checksum,size,storage_key,createdAt) VALUES(1,1,1,?,?,?,CURRENT_TIMESTAMP)",[require('node:crypto').createHash('sha256').update(content).digest('hex'),Buffer.byteLength(content),'asset-1/revisions/1/content']);await db.close();
 const file=path.join(h.data,'config-assets/asset-1/revisions/1/content');await fs.mkdir(path.dirname(file),{recursive:true,mode:0o700});await fs.writeFile(file,'damaged',{mode:0o600});const backup=new BackupCoordinator(h.paths);await assert.rejects(backup.create(),/BACKUP_CONFIG_INTEGRITY_FAILED/);assert.deepEqual(await backup.list(),[]);await fs.writeFile(file,content);await backup.create();
 const bare=path.join(h.data,'git/example.test/repository-1.git');await fs.mkdir(path.dirname(bare),{recursive:true,mode:0o700});execFileSync('git',['init','--bare',bare],{stdio:'pipe'});const object=execFileSync('git',['--git-dir',bare,'hash-object','-w','--stdin'],{input:'unique object',encoding:'utf8'}).trim();const objectFile=path.join(bare,'objects',object.slice(0,2),object.slice(2));await fs.chmod(objectFile,0o600);await fs.writeFile(objectFile,'corrupt');
 const write=await backupDatabase(path.join(h.data,'db/database.sqlite'),true);await write.all("INSERT INTO Repositories(id,name,provider,remote_url,normalized_url,host,storage_state,storage_path,createdAt,updatedAt) VALUES(1,'fixture','generic','https://example.test/unavailable','https://example.test/unavailable','example.test','READY',?,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP)",[bare]);await write.close();await assert.rejects(backup.create(),/BACKUP_GIT/);assert.equal((await backup.list()).length,1);
});
test('portable failures clear caller passphrase buffers and publish no partial export',async t=>{
 const h=await fixture(t),backup=new BackupCoordinator(h.paths),id=await backup.create();const invalid=Buffer.from('UNIQUE_SUPER_SECRET_PASSPHRASE');await assert.rejects(backup.export('../invalid',invalid));assert.ok(invalid.every(byte=>byte===0));
 const missing=Buffer.from('UNIQUE_SUPER_SECRET_PASSPHRASE');await assert.rejects(backup.import(path.join(h.root,'absent'),missing));assert.ok(missing.every(byte=>byte===0));assert.deepEqual(await fs.readdir(await h.paths.bucket('imports')),[]);
 const empty=Buffer.alloc(0);await assert.rejects(backup.export(id,empty),/BACKUP_PASSPHRASE_INVALID/);assert.deepEqual(await fs.readdir(await h.paths.bucket('exports')),[]);assert.deepEqual(await fs.readdir(await h.paths.bucket('.staging')),[]);
});
test('Run log validation rejects a directory or safe symlink in place of a log',async t=>{
 const h=await fixture(t),db=await backupDatabase(path.join(h.data,'db/database.sqlite'),true);await db.all("INSERT INTO TaskRuns(id,task_id,status,trigger_type,submitted_at,log_identity,concurrency_policy,createdAt,updatedAt) VALUES(1,NULL,'SUCCESS','API',CURRENT_TIMESTAMP,'log-fixture','ALLOW',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP)");await db.close();const file=path.join(h.data,'log/task-runs/run-1.log');await fs.mkdir(file,{recursive:true,mode:0o700});const validator=new BackupCoordinator(h.paths).validator;await assert.rejects(validator.domains(h.data),/BACKUP_LOG_INVALID/);await fs.rmdir(file);await fs.writeFile(path.join(path.dirname(file),'other'),'log',{mode:0o600});await fs.symlink('other',file);await assert.rejects(validator.domains(h.data),/BACKUP_LOG_INVALID/);
});
test('failed managed resource remains visible and prevents a false successful rebuild',async t=>{
 const h=await fixture(t),db=await backupDatabase(path.join(h.data,'db/database.sqlite'),true);await db.all("INSERT INTO RuntimeProviders(id,language,provider_type,state,install_root,createdAt,updatedAt) VALUES(1,'PYTHON','PYENV','READY','runtime/python/pyenv',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP)");await db.all("INSERT INTO RuntimeInstallations(id,provider_id,language,implementation,version,state,executable_relative_path,last_error,createdAt,updatedAt) VALUES(1,1,'PYTHON','CPYTHON','3.13.15','ERROR','bin/python','INSTALL_FAILED',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP)");await db.close();const reconciler=new(require('../../back/services/backup/runtimeRestore.ts').RuntimeRestoreReconciler)();assert.equal((await reconciler.plan(h.data)).python_runtimes[0].id,1);await assert.rejects(new(require('../../back/services/backup/rebuild.ts').RestoreRebuildService)(h.paths,{}).run(),/RESTORE_REBUILD_FAILED/);
 const write=await backupDatabase(path.join(h.data,'db/database.sqlite'),true);await write.all("UPDATE RuntimeInstallations SET state='READY',last_error=NULL");await write.close();assert.equal((await reconciler.plan(h.data)).python_runtimes.length,0);
});
test('runtime restore invalidates physical Python provider while retaining logical Node catalog provider',async t=>{
 const h=await fixture(t),db=await backupDatabase(path.join(h.data,'db/database.sqlite'),true);await db.all("INSERT INTO RuntimeProviders(id,language,provider_type,state,install_root,createdAt,updatedAt) VALUES(1,'PYTHON','PYENV','READY','runtime/python/pyenv',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),(2,'NODE','NODE_DISTRIBUTION','READY','runtime/node',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP)");await db.close();await new(require('../../back/services/backup/runtimeRestore.ts').RuntimeRestoreReconciler)().reconcile(h.data);const restored=await backupDatabase(path.join(h.data,'db/database.sqlite'));assert.deepEqual((await restored.all('SELECT state FROM RuntimeProviders ORDER BY id')).map(r=>r.state),['MISSING','READY']);await restored.close();
});
