const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs/promises'),os=require('node:os'),path=require('node:path');
const {attach}=require('../phase10/attach.cjs'),{task,wait}=require('../phase10/helpers.cjs');
const manifest=require('../../diagnostics/phase11/managed-node/result.json');
test('official managed Node executes CJS, ESM and real tsx using pinned Builds; bindings restore and conflicts fail closed',async t=>{
 assert.equal(manifest.status,'PASS');const root=manifest.root;
 const h=await attach(root);h.taskService=new(h.load('back/services/task.ts').default)();t.after(async()=>{await h.close();});
 const ops=h.execution.resolver.operations,s=ops.node,runtime=(await s.runtimes()).find(row=>row.state==='READY'),tool=(await s.toolchains()).find(row=>row.manager_type==='NPM'&&row.state==='READY');
 let environment=await s.definition({name:'phase10 actual node deps '+Date.now(),runtime_id:runtime.id,toolchain_id:tool.id,dependencies:[{name:'is-number',specifier:'7.0.0',type:'DEPENDENCY'},{name:'tsx',specifier:'4.20.6',type:'DEPENDENCY'}],install_scripts_policy:'ALLOW'});
 const buildOp=await ops.request('NODE_ENV_BUILD',{node:{environment_id:environment.id,expected_version:environment.version},timeout_seconds:180});const done=await ops.wait(buildOp.id);assert.equal(done.status,'SUCCESS',await fs.readFile(await ops.paths.log(done.id),'utf8'));environment=await s.environment(environment.id);const first=environment.current_build_id;
 async function define(entry,code,language='JAVASCRIPT',settings={}){const f=await task(h,code,settings,{entry,language,arguments:['space argument'],runtime:{kind:'NODE',node_environment_id:environment.id,python_environment_id:null}});await h.TaskRuntimeBindingModel.update({node_environment_id:environment.id},{where:{task_id:f.definition.id}});return f;}
 const cases=[['jobs/main.cjs',"const n=require('is-number');console.log('CJS',n(12),process.execPath,process.argv[2]);"],['jobs/main.mjs',"import n from 'is-number';console.log('ESM',n(12),process.execPath,process.argv[2]);"],['jobs/main.ts',"import n from 'is-number';const value: number=12;console.log('TSX',n(value),process.execPath,process.argv[2]);"]];
 for(const [entry,code] of cases){const f=await define(entry,code,entry.endsWith('.ts')?'TYPESCRIPT':'JAVASCRIPT'),run=await h.execution.submit(f.definition.id),result=await wait(h,run.id,30000);assert.equal(result.status,'SUCCESS',JSON.stringify(result));assert.equal(result.snapshot_metadata.build_id,first);const log=await h.execution.log(run.id);assert.ok(log.includes('true'));assert.ok(log.includes('space argument'));assert.ok(log.includes('/runtime/node/versions/runtime-'));await assert.rejects(fs.lstat(path.join(f.root,'node_modules')),{code:'ENOENT'});await require('../phase10/managed-entrypoints.cjs')(h,f.definition);}
 const conflict=await define('jobs/conflict.cjs',"console.log('must-not-run')");await fs.mkdir(path.join(conflict.root,'jobs/node_modules'));const failed=await wait(h,(await h.execution.submit(conflict.definition.id)).id);assert.equal(failed.status,'FAILED');assert.equal(failed.error_code,'NODE_MODULES_CONFLICT');assert.ok((await fs.stat(path.join(conflict.root,'jobs/node_modules'))).isDirectory());
 const retry=await define('retry.cjs',"const fs=require('fs');console.log(require('is-number/package.json').version);if(!fs.existsSync('once')){fs.writeFileSync('once','');process.exit(3)}",'JAVASCRIPT',{max_attempts:2,initial_delay_seconds:8});const run=await h.execution.submit(retry.definition.id);await h.execution.tick();
 for(let i=0;i<100;i++){if(await h.TaskRunAttemptModel.count({where:{task_run_id:run.id,status:'FAILED'}}))break;await new Promise(r=>setTimeout(r,30));}
 environment=await s.environment(environment.id);environment=await s.definition({name:environment.name,runtime_id:runtime.id,toolchain_id:tool.id,dependencies:[{name:'is-number',specifier:'6.0.0',type:'DEPENDENCY'}],expected_version:environment.version},environment.id);
 const next=await ops.request('NODE_ENV_BUILD',{node:{environment_id:environment.id,expected_version:environment.version},timeout_seconds:180});assert.equal((await ops.wait(next.id)).status,'SUCCESS');assert.notEqual((await s.environment(environment.id)).current_build_id,first);
 const result=await wait(h,run.id,30000);assert.equal(result.status,'SUCCESS');assert.equal(result.snapshot_metadata.build_id,first);assert.equal((await h.execution.log(run.id)).split('7.0.0').length-1,2);
 const newRun=await wait(h,(await h.execution.submit(retry.definition.id)).id,30000);assert.equal(newRun.status,'SUCCESS');assert.ok((await h.execution.log(newRun.id)).includes('6.0.0'));
 const slow=await define('slow.cjs','setTimeout(()=>{},30000)', 'JAVASCRIPT',{timeout_seconds:1});const timed=await wait(h,(await h.execution.submit(slow.definition.id)).id);assert.equal(timed.status,'TIMEOUT');const cancel=await h.execution.submit(slow.definition.id);await h.execution.tick();await new Promise(r=>setTimeout(r,200));await h.execution.cancel(cancel.id);assert.equal((await wait(h,cancel.id)).status,'CANCELLED');
 const ts=await define('missing.ts','const x: number=1;console.log(x)','TYPESCRIPT');const missing=await wait(h,(await h.execution.submit(ts.definition.id)).id);assert.equal(missing.status,'FAILED');assert.equal(missing.attempt_count,0);
 await fs.writeFile('diagnostics/phase11/managed-node-execution.json',JSON.stringify({status:'PASS',node:runtime.version,tsx:'4.20.6',cjs:true,esm:true,typescript:true,nested_conflict:true,scheduled_cjs_esm_ts:true,timeout:true,cancel:true,pinned_build:first,promoted_build:(await s.environment(environment.id)).current_build_id},null,2));
});
