const {test}=require('node:test'),assert=require('node:assert/strict'),http=require('node:http'),fs=require('node:fs/promises');
const {fixture,task,wait}=require('../phase10/helpers.cjs');
const {QueryTypes}=require('sequelize');
const rows=(h,sql,replacements={})=>h.db.query(sql,{type:QueryTypes.SELECT,replacements});
async function setup(t){const h=await fixture(t),f=await task(h,'exit 0');const Channels=h.load('back/services/notificationChannels.ts').default,Dispatcher=h.load('back/services/notificationDispatcher.ts').default;h.channels=new Channels();h.dispatcher=new Dispatcher(undefined,h.channels,1,2);h.dispatcher.paths.dataRoot=h.root;const messages=[];let fail=false;const receiver=http.createServer(async(req,res)=>{let body='';for await(const b of req)body+=b;messages.push({body:JSON.parse(body),key:req.headers['idempotency-key']});res.writeHead(fail?500:200);res.end('{}');});await new Promise(r=>receiver.listen(0,'127.0.0.1',r));t.after(()=>new Promise(r=>receiver.close(r)));const channel=await h.channels.save({name:'fixture',type:'WEBHOOK',is_default:true,secret:{url:`http://127.0.0.1:${receiver.address().port}/send`,authorization:'Bearer channel-secret'}});return{h,f,messages,channel,fail:value=>fail=value};}
async function policy(h,id,patch={}){const old=await h.channels.policy(id);return h.channels.savePolicy(id,{enabled:true,notify_success:false,notify_failure:true,notify_timeout:true,notify_interrupted:true,notify_cancelled:false,notify_recovery:true,failure_threshold:3,repeat_every_failures:0,channel_mode:'DEFAULT',channels:[],expected_version:old.version,...patch});}
async function finish(h,id,status){const run=await h.execution.submit(id);await h.TaskRunModel.update({status,finished_at:new Date(),result_code:status},{where:{id:run.id}});return run;}
test('threshold, recovery, per-status overrides, atomic outbox and real HTTP delivery',async t=>{
 const {h,f,messages}=await setup(t);await policy(h,f.definition.id);for(let i=0;i<4;i++)await finish(h,f.definition.id,'FAILED');assert.equal((await rows(h,'SELECT * FROM NotificationOutbox')).length,1);const [health]=await rows(h,'SELECT * FROM TaskHealthStates');assert.equal(health.consecutive_failures,4);assert.equal(health.failure_alert_open,1);
 await h.dispatcher.tick();assert.equal(messages.length,1);assert.equal(messages[0].body.event,'FAILED');assert.equal((await h.dispatcher.list())[0].status,'SENT');
 await finish(h,f.definition.id,'CANCELLED');assert.equal((await rows(h,'SELECT consecutive_failures FROM TaskHealthStates'))[0].consecutive_failures,4);
 await finish(h,f.definition.id,'SUCCESS');await h.dispatcher.tick();assert.equal(messages.length,2);assert.equal(messages[1].body.event,'RECOVERY');assert.equal((await rows(h,'SELECT * FROM TaskHealthStates'))[0].failure_alert_open,0);
 await finish(h,f.definition.id,'SUCCESS');await h.dispatcher.tick();assert.equal(messages.length,2);
 await policy(h,f.definition.id,{failure_threshold:1,notify_timeout:false});await finish(h,f.definition.id,'TIMEOUT');assert.equal((await rows(h,'SELECT * FROM NotificationOutbox')).length,2);
 const publicData=JSON.stringify(await h.channels.list());assert.ok(!publicData.includes('channel-secret'));assert.ok(!publicData.includes('/send'));
});
test('delivery retry/dead/manual identity and channel archive preserve history; execution does not wait',async t=>{
 const {h,f,fail,channel,messages}=await setup(t);await policy(h,f.definition.id,{notify_success:true});fail(true);const r=await h.execution.submit(f.definition.id);assert.equal((await wait(h,r.id)).status,'SUCCESS');assert.equal(messages.length,0);await h.dispatcher.tick();let out=(await h.dispatcher.list())[0];assert.equal(out.status,'RETRY');await new Promise(r=>setTimeout(r,5));await h.dispatcher.tick();out=(await h.dispatcher.list())[0];assert.equal(out.status,'DEAD');assert.deepEqual((await h.execution.get(r.id)).result.secondaryErrors,[]);fail(false);await h.dispatcher.retry(out.id);await h.dispatcher.tick();assert.equal((await h.dispatcher.list())[0].status,'SENT');assert.equal((await h.dispatcher.attempts(out.id)).length,3);
 const info=await h.channels.get(channel.id);await h.channels.archive(channel.id,info.version);await assert.rejects(h.channels.send(channel.id,{},'x'),/CHANNEL_DISABLED/);assert.equal((await h.dispatcher.list()).length,1);
});
test('run events are ordered, attempts retain retry results, resource/log APIs omit secret values',async t=>{
 const h=await fixture(t),f=await task(h,'printf "分段😀"; if [ ! -f marker ]; then touch marker; exit 2; fi',{max_attempts:2,initial_delay_seconds:0});const run=await h.execution.submit(f.definition.id);await wait(h,run.id);const Obs=h.load('back/services/runObservability.ts').default,o=new Obs();const events=await o.events(run.id);assert.deepEqual(events.map(e=>e.sequence),events.map((_,i)=>i+1));for(const type of ['RUN_SUBMITTED','RUN_QUEUED','RUN_RESOLVING','ATTEMPT_STARTED','BEFORE_STARTED','MAIN_STARTED','FINALLY_FINISHED','RETRY_SCHEDULED','RUN_SUCCESS'])assert.ok(events.some(e=>e.type===type),type);const attempts=await o.attempts(run.id);assert.equal(attempts.length,2);assert.equal(attempts[0].retry_decision,1);assert.equal(attempts[0].result.status,'FAILED');
 const Log=h.load('back/services/runLog.ts').default,log=new Log(h.paths);let cursor,content='';for(let i=0;i<100;i++){const chunk=await log.read(run.id,{tail:false,limit:7,cursor});content+=chunk.content;cursor=chunk.cursor;if(chunk.terminal)break;}assert.equal(content,await h.execution.log(run.id));assert.ok(!content.includes('\ufffd'));await assert.rejects(log.read(run.id,{raw:true}),/LOG_QUERY_INVALID/);
});
test('terminal transaction rollback includes health and outbox',async t=>{const {h,f}=await setup(t);await policy(h,f.definition.id,{failure_threshold:1});const run=await h.execution.submit(f.definition.id);await assert.rejects(h.db.transaction(async transaction=>{await h.TaskRunModel.update({status:'FAILED',finished_at:new Date()},{where:{id:run.id},transaction});throw Error('fault');}),/fault/);assert.equal((await h.execution.get(run.id)).status,'QUEUED');assert.equal((await rows(h,'SELECT * FROM TaskHealthStates'))[0].consecutive_failures,0);assert.equal((await rows(h,'SELECT * FROM NotificationOutbox')).length,0);await finish(h,f.definition.id,'SKIPPED');});

test('channel modes, optimistic secret updates and task clone preserve explicit notification semantics',async t=>{
 const {h,f,channel}=await setup(t);let c=await h.channels.get(channel.id);
 await h.channels.save({name:c.name,type:c.type,enabled:true,is_default:true,expected_version:c.version,secret_action:'KEEP'},c.id);
 await assert.rejects(h.channels.save({name:c.name,type:c.type,expected_version:c.version,secret_action:'KEEP'},c.id),/CHANNEL_VERSION_CONFLICT/);
 await policy(h,f.definition.id,{failure_threshold:1,channel_mode:'NONE'});await finish(h,f.definition.id,'FAILED');assert.equal((await rows(h,'SELECT * FROM NotificationOutbox')).length,0);
 await policy(h,f.definition.id,{failure_threshold:1,channel_mode:'EXPLICIT',channels:[]});await finish(h,f.definition.id,'FAILED');assert.equal((await rows(h,'SELECT * FROM NotificationOutbox')).length,0);
 await policy(h,f.definition.id,{failure_threshold:1,channel_mode:'EXPLICIT',channels:[channel.id]});await finish(h,f.definition.id,'FAILED');assert.equal((await rows(h,'SELECT * FROM NotificationOutbox')).length,1);
 const cloned=await h.taskService.clone(f.definition.id,'cloned policy');const copied=await h.channels.policy(cloned.id);assert.equal(copied.channel_mode,'EXPLICIT');assert.deepEqual(copied.channels,[channel.id]);
 c=await h.channels.get(channel.id);await h.channels.save({name:c.name,type:c.type,expected_version:c.version,secret_action:'DELETE'},c.id);assert.equal((await h.channels.get(c.id)).secret_configured,0);await assert.rejects(h.channels.send(c.id,{},'missing'),/CHANNEL_SECRET_MISSING/);
});
