const {test}=require('node:test'),assert=require('node:assert/strict');const {fixture,QueryTypes}=require('../phase5/helpers.cjs');const v8=require('../../back/schema/platform-v8.json');
async function seed(h){for(const o of [...v8.objects].sort((a,b)=>Number(!a.sql.startsWith('CREATE TABLE'))-Number(!b.sql.startsWith('CREATE TABLE'))))await h.db.query(o.sql);await h.db.query('INSERT INTO PlatformMetadata VALUES (:platform_schema_version,:model_signature,:schema_signature)',{replacements:v8.metadata});}
const objects=h=>h.db.query("SELECT name,sql FROM sqlite_master WHERE name NOT LIKE 'sqlite_%' ORDER BY type,name",{type:QueryTypes.SELECT});
test('actual frozen v8 migrates to identical fresh v9; rollback/retry/history and legacy policy preserved',async t=>{const fresh=await fixture(t),h=await fixture(t,{initialize:false});await seed(h);for(const [i,mode]of ['NONE','FAILURE','SUCCESS','ALWAYS'].entries()){await h.db.query(`INSERT INTO Tasks(id,name,createdAt,updatedAt) VALUES(:id,:mode,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP)`,{replacements:{id:i+1,mode}});await h.db.query('INSERT INTO TaskExecutionSettings(task_id,notification,createdAt,updatedAt) VALUES(:id,:mode,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP)',{replacements:{id:i+1,mode}});}
 await h.db.query("INSERT INTO TaskRuns(id,task_id,status,submitted_at,finished_at,trigger_type,log_identity,concurrency_policy,createdAt,updatedAt) VALUES(1,2,'FAILED',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'MANUAL','history','QUEUE',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP)");await h.db.query("INSERT INTO TaskRunAttempts(task_run_id,attempt_number,status,started_at,createdAt,updatedAt) VALUES(1,1,'FAILED',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP)");

 await h.db.query("INSERT INTO TaskTriggers(id,task_id,type,createdAt,updatedAt) VALUES(1,2,'WEBHOOK',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP)");await h.db.query("INSERT INTO TriggerEvents(id,trigger_id,task_id,event_key,trigger_type,status,task_run_id,received_at,createdAt,updatedAt) VALUES(1,1,2,'old-event','WEBHOOK','SUBMITTED',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP)");
 await h.db.query("INSERT INTO Auths(type,info,createdAt,updatedAt) VALUES('notification',:info,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP)",{replacements:{info:JSON.stringify({type:'bark',barkPush:'migration-secret'})}});
 // Same timestamps: order is completion timestamp then run ID, including intervening neutral outcomes.
 for(const [id,status]of [[2,'SUCCESS'],[3,'FAILED'],[4,'CANCELLED'],[5,'SKIPPED']])await h.db.query("INSERT INTO TaskRuns(id,task_id,status,submitted_at,finished_at,trigger_type,log_identity,concurrency_policy,createdAt,updatedAt) VALUES(:id,3,:status,'2025-01-01','2025-01-01','MANUAL','tie-' || :id,'QUEUE',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP)",{replacements:{id,status}});
 const original=h.db.query.bind(h.db);let failed=false;h.db.query=async(sql,...args)=>{if(!failed&&String(sql).includes('CREATE TRIGGER run_terminal_insert_observability')){failed=true;throw Error('late fault');}return original(sql,...args);};await assert.rejects(h.initializeOperationalSchema(h.db,h.models),/late fault/);h.db.query=original;assert.equal((await h.db.query('SELECT platform_schema_version FROM PlatformMetadata',{type:QueryTypes.SELECT}))[0].platform_schema_version,8);await h.initializeOperationalSchema(h.db,h.models);assert.equal(h.schemaSignature(await objects(h)),fresh.schemaSignature(await objects(fresh)));assert.equal(await h.TaskRunModel.count(),5);assert.equal(await h.TaskRunAttemptModel.count(),1);const policies=await h.db.query('SELECT * FROM TaskNotificationPolicies ORDER BY task_id',{type:QueryTypes.SELECT});assert.deepEqual(policies.map(p=>[p.enabled,p.notify_success,p.notify_failure,p.notify_timeout,p.notify_interrupted,p.notify_cancelled,p.repeat_every_failures]),[[0,0,0,0,0,0,1],[1,0,1,1,1,1,1],[1,1,0,0,0,0,1],[1,1,1,1,1,1,1]]);assert.equal((await h.db.query('SELECT consecutive_failures FROM TaskHealthStates WHERE task_id=2',{type:QueryTypes.SELECT}))[0].consecutive_failures,1);assert.equal((await h.db.query('SELECT COUNT(*) n FROM TaskTriggers',{type:QueryTypes.SELECT}))[0].n,1);assert.equal((await h.db.query('SELECT task_run_id FROM TriggerEvents',{type:QueryTypes.SELECT}))[0].task_run_id,1);assert.equal((await h.db.query('SELECT consecutive_failures FROM TaskHealthStates WHERE task_id=3',{type:QueryTypes.SELECT}))[0].consecutive_failures,1);assert.equal((await h.db.query('SELECT last_run_id FROM TaskHealthStates WHERE task_id=3',{type:QueryTypes.SELECT}))[0].last_run_id,5);assert.equal((await h.db.query('SELECT secret FROM NotificationChannels',{type:QueryTypes.SELECT}))[0].secret,JSON.stringify({barkPush:'migration-secret'}));for(const taskId of [1,2,3,4])for(const status of ['SUCCESS','FAILED','TIMEOUT','INTERRUPTED','CANCELLED','SKIPPED'])await h.db.query("INSERT INTO TaskRuns(task_id,status,submitted_at,finished_at,trigger_type,log_identity,concurrency_policy,createdAt,updatedAt) VALUES(:taskId,:status,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'MANUAL',:identity,'QUEUE',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP)",{replacements:{taskId,status,identity:'mode-'+taskId+'-'+status}});const counts=await h.db.query('SELECT task_id,COUNT(*) n FROM NotificationOutbox GROUP BY task_id ORDER BY task_id',{type:QueryTypes.SELECT});assert.deepEqual(counts.map(x=>[x.task_id,x.n]),[[2,4],[3,1],[4,5]]);assert.deepEqual(await h.db.query('PRAGMA foreign_key_check',{type:QueryTypes.SELECT}),[]);await h.initializeOperationalSchema(h.db,h.models);});
