const test = require('node:test'), assert = require('node:assert/strict');
const setup = require('../phase4/helpers.cjs');
async function resources(h) {
  const repo = await h.RepositoryModel.create({ name: 'repo', provider: 'generic', remote_url: 'https://example.invalid/a', normalized_url: 'example.invalid/a' });
  const sub = await h.SubscriptionModel.create({ name: 'sub', repository_id: repo.id });
  const task = await h.SchedulerProjectionModel.create({ name: 'task', command: 'task a.py', sub_id: sub.id });
  return { repo, sub, task };
}
test('profile CRUD, uniqueness, default, clone secrets, and reference protection', async t => {
  const h = await setup(t), { repo, sub, task } = await resources(h);
  const p = await h.profiles.save({ repository_id: repo.id, name: 'prod', is_default: true });
  assert.equal(p.is_default, true);
  await assert.rejects(h.profiles.save({ repository_id: repo.id, name: 'prod' }), /ENV_PROFILE_SAVE_CONFLICT/);
  await h.variables.save('repository', p.id, [{ name: 'TOKEN', value: 'secret-fixture', is_secret: true }]);
  const clone = await h.profiles.clone(p.id, 'test');
  assert.equal(clone.variables_count, 1);
  assert.doesNotMatch(JSON.stringify(await h.variables.list('repository', clone.id)), /secret-fixture/);
  await assert.rejects(h.profiles.remove(p.id), /ENV_PROFILE_IN_USE/);
  await h.profiles.save({ id: p.id, is_default: false });
  await h.variables.bind('subscription', sub.id, p.id);
  await assert.rejects(h.profiles.remove(p.id), /ENV_PROFILE_IN_USE/);
  await h.variables.bind('subscription', sub.id, null);
  await h.variables.bind('task', task.id, p.id);
  await assert.rejects(h.profiles.remove(p.id), /ENV_PROFILE_IN_USE/);
  await h.variables.bind('task', task.id, null);
  await h.profiles.remove(p.id);
  assert.equal(await h.RepositoryEnvVariableModel.count({ where: { profile_id: p.id } }), 0);
});
test('secret keep/replace/clear, metadata edits, atomic batch rollback and safe errors', async t => {
  const h = await setup(t), { task } = await resources(h);
  const save = patches => h.variables.save('task', task.id, patches);
  const first = await save([{ name: 'TOKEN', value: 'private-test-value', is_secret: true }]);
  assert.equal(first[0].value, null); assert.equal(first[0].has_value, true);
  await save([{ name: 'TOKEN', status: 'disabled' }]);
  assert.equal((await h.TaskEnvVariableModel.unscoped().findOne()).value, 'private-test-value');
  await assert.rejects(save([{ name: 'TOKEN', value: 'replacement' }]), /ENV_SECRET_UPDATE_INVALID/);
  await save([{ name: 'TOKEN', value: 'replacement', replace_secret: true, status: 'enabled' }]);
  await assert.rejects(save([{ name: 'GOOD', value: '1' }, { name: 'bad-name', value: 'private-test-value' }]), /ENV_NAME_INVALID/);
  assert.equal(await h.TaskEnvVariableModel.count({ where: { name: 'GOOD' } }), 0);
  await assert.rejects(save([{ name: 'TOKEN', is_secret: false }]), /ENV_SECRET_UPDATE_INVALID/);
  await assert.rejects(save([{ name: 'X', value: 'a\0b' }]), /ENV_VALUE_INVALID/);
  assert.doesNotMatch(JSON.stringify(await h.resolver.preview(task.id)), /private-test-value|replacement/);
  assert.doesNotMatch(JSON.stringify(h.logs), /private-test-value|replacement"/);
  await save([{ name: 'TOKEN', clear: true }]);
  assert.equal(await h.TaskEnvVariableModel.count(), 0);
});
test('profile precedence, manual task, disabled and wrong repository fail closed', async t => {
  const h = await setup(t), { repo, sub, task } = await resources(h);
  const ps = [];
  for (const name of ['default', 'subscription', 'task']) ps.push(await h.profiles.save({ repository_id: repo.id, name, is_default: name === 'default' }));
  assert.equal((await h.resolver.resolve(task.id)).profile.id, ps[0].id);
  await h.variables.bind('subscription', sub.id, ps[1].id);
  assert.equal((await h.resolver.resolve(task.id)).profile.id, ps[1].id);
  await h.variables.bind('task', task.id, ps[2].id);
  assert.equal((await h.resolver.resolve(task.id)).profile.id, ps[2].id);
  await h.profiles.save({ id: ps[2].id, status: 'disabled' });
  await assert.rejects(h.resolver.resolve(task.id), /ENV_PROFILE_DISABLED/);
  const manual = await h.SchedulerProjectionModel.create({ command: 'task manual.py' });
  await assert.rejects(h.variables.bind('task', manual.id, ps[0].id), /ENV_PROFILE_REPOSITORY_MISMATCH/);
  await assert.rejects(h.variables.bind('task', task.id, 99999), /ENV_PROFILE_NOT_FOUND/);
  assert.equal((await h.resolver.resolve(manual.id)).metadata.scoped, true);
  await h.variables.save('task', manual.id, [{ name: 'MANUAL', value: 'yes' }]);
  assert.equal((await h.resolver.resolve(manual.id)).variables.MANUAL, 'yes');
  await h.TaskModel.destroy({where:{id:manual.id}}); assert.equal(await h.TaskEnvVariableModel.count(), 0);
});
test('SET/UNSET/disabled/empty precedence, immutable snapshot and parent isolation', async t => {
  const h = await setup(t), { repo, task } = await resources(h);
  const p = await h.profiles.save({ repository_id: repo.id, name: 'prod', is_default: true });
  await h.EnvModel.bulkCreate(['A', 'B', 'C', 'D'].map(name => ({ name, value: 'global', status: 0 })));
  await h.variables.save('repository', p.id, [{ name: 'A', operation: 'UNSET' }, { name: 'B', value: 'repo' }, { name: 'C', value: 'repo', status: 'disabled' }]);
  await h.variables.save('task', task.id, [{ name: 'A', value: 'task' }, { name: 'B', operation: 'UNSET' }, { name: 'D', value: '' }, { name: 'HOST', operation: 'UNSET' }, { name: 'C', value: 'ignored', status: 'disabled' }]);
  const base = { HOST: 'host', PATH: 'kept' }, result = await h.resolver.resolve(task.id, base);
  assert.deepEqual({ ...result.variables }, { PATH: 'kept', A: 'task', C: 'global', D: '' });
  assert.deepEqual(new Set(result.unsetVariables), new Set(['B', 'HOST']));
  assert.equal(result.origins.A, 'TASK'); assert.equal(result.origins.C, 'GLOBAL');
  assert.equal(base.HOST, 'host'); assert.equal(Object.isFrozen(result.variables), true);
  await h.variables.save('task', task.id, [{ name: 'A', value: 'next' }]);
  assert.equal(result.variables.A, 'task'); assert.equal((await h.resolver.resolve(task.id)).variables.A, 'next');
});
test('Global unique contract masks secrets across SDK responses and rejects inherited backend secrets',async t=>{
 const h=await setup(t);
 await h.variables.save('global',0,[{name:'FOO',value:' A '},{name:'EMPTY',value:''},{name:'SECRET',value:'private-global',is_secret:true},{name:'DISABLED',value:'no',status:'disabled'}]);
 const rows=await h.variables.list('global',0);assert.equal(rows.find(x=>x.name==='SECRET').value,null);assert.equal(rows.find(x=>x.name==='FOO').value,' A ');
 await assert.rejects(h.EnvModel.create({name:'FOO',value:'duplicate'}));
 await h.variables.save('global',0,[{name:'SECRET',position:4}]);
 await assert.rejects(h.variables.save('global',0,[{name:'SECRET',value:'new'}]),/ENV_SECRET_UPDATE_INVALID/);
 await h.variables.save('global',0,[{name:'SECRET',value:'replaced-private',replace_secret:true}]);
 const a=await h.resolver.resolve(null,{PATH:process.env.PATH,JWT_SECRET:'backend-private',INTERNAL_TOKEN:'backend-token'});
 assert.equal(a.variables.FOO,' A ');assert.equal(a.variables.EMPTY,'');assert.equal(a.variables.DISABLED,undefined);assert.equal(a.variables.JWT_SECRET,undefined);assert.equal(a.variables.INTERNAL_TOKEN,undefined);assert.equal(a.variables.SECRET,'replaced-private');
 assert.doesNotMatch(JSON.stringify(await h.globals.envs()),/replaced-private/);assert.doesNotMatch(JSON.stringify(h.logs),/private-global|replaced-private/);
 await h.variables.save('global',0,[{name:'FOO',operation:'UNSET'},{name:'SECRET',clear:true}]);
 assert.equal((await h.resolver.resolve(null)).variables.FOO,undefined);assert.equal(a.variables.FOO,' A ');
});
