const fs=require('fs'),assert=require('node:assert/strict'),{execFileSync}=require('child_process');
const files=['back/services/taskTrigger.ts','back/services/triggerEvents.ts','back/services/triggerScheduler.ts','back/services/gitUpdateTrigger.ts','back/services/discovery.ts','back/services/discoveryScanner.ts','back/api/triggerWebhook.ts'];
const violations=[];for(const file of files){const source=fs.readFileSync(file,'utf8');for(const pattern of [/child_process/,/\bspawn\s*\(/,/new\s+ExecutionResolver/,/SchedulerProjection/,/crontab\.list/,/SubscriptionDiscoveryAdapter/,/ExecutionAttemptCoordinator/])if(pattern.test(source))violations.push({file,pattern:String(pattern)});}
const task=fs.readFileSync('back/data/task.ts','utf8');assert.ok(!/^\s+schedule\s*:/m.test(task));
for(const file of ['back/api/tasks.ts','back/loaders/initData.ts','back/loaders/bootAfter.ts','back/services/managedSubscription.ts'])assert.ok(!/autosave_crontab|mutateTaskDefinitions|SchedulerBridgeService|SubscriptionDiscoveryAdapter|\.stage\(/.test(fs.readFileSync(file,'utf8')),file);
assert.equal(fs.existsSync('back/services/subscriptionDiscovery.ts'),false);assert.deepEqual(violations,[]);
const shellReferences=execFileSync('rg',['-n','node-schedule|crontab\\.list|executionSubmission|taskRunSubmit','back','shell'],{encoding:'utf8'}).split('\n').filter(Boolean);
const report={status:'PASS',trigger_boundary_violations:violations,task_schedule_removed:true,normal_task_projection_removed:true,discovery_staging_adapter_removed:true,retained_reference_classification:{'B01':'existing script editor / staging / recovery sources','B02_B03':'historical Shell and protected launcher; physical cleanup BLOCKED_BY_LINUX_GATE','B04':'Subscription and system maintenance scheduling; historical Task RPC / recovery adapters outside normal path','B09_B10':'bootstrap / platform dependencies, Linux packages','B14_B15':'historical logs, statistics and projection APIs'},retained_reference_inventory:shellReferences};
fs.writeFileSync('diagnostics/phase11/static-audit.json',JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify({status:report.status,retained_references:shellReferences.length}));
