const acceptance=require('../../scripts/ci/acceptance.cjs');
const evidenceDirectory=acceptance.output(__dirname);
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),{execFileSync}=require('node:child_process');
module.exports=async({page,base,checked,api,until,mark,tmp,env,root,stop,start,login,shellTask,tasks,hook,cron,gitTrigger,origin,git,messages})=>{
 assert.equal((await fetch(base+'/api/backups')).status,401);
 for (const action of ['export','import']) assert.equal(await page.evaluate(async action => (await fetch('/api/system/data/'+action,{method:'PUT',headers:{Authorization:'Bearer '+localStorage.getItem('token')}})).status,action),404);
 mark('backup-panel-auth-and-legacy-routes-absent');
 const backupPage=async()=>{await page.goto(base+'/setting');await page.getByRole('tab',{name:'备份与恢复',exact:true}).click();await page.getByRole('button',{name:'创建备份',exact:true}).waitFor();};
 const waitOperation=async(kind)=>{
  const started=Date.now();
  try { await until(async()=>{const text=await page.locator('body').innerText();if(text.includes(kind+': FAILED'))throw Error(text.slice(-2000));return text.includes(kind+': SUCCESS');}); }
  catch(error) {
   const samples=[];
   // Failure-only observation preserves the original assertion and deadline. It
   // distinguishes a live long operation from a stuck worker without passing it.
   const deadline=Date.now()+(kind==='REBUILD'?120000:0);
   do {
    try { const rows=await checked('/runtime/python/operations'); samples.push({elapsed_ms:Date.now()-started,operations:rows.map(row=>Object.fromEntries(['id','operation_type','status','stage','started_at','finished_at','error_code'].map(key=>[key,row[key]])))}); }
    catch { samples.push({elapsed_ms:Date.now()-started,error_code:'OPERATION_DIAGNOSTIC_UNAVAILABLE'});break; }
    const text=await page.locator('body').innerText();if(text.includes(kind+': SUCCESS')||text.includes(kind+': FAILED'))break;
    if(Date.now()>=deadline)break;
    await new Promise(resolve=>setTimeout(resolve,2000));
   }while(Date.now()<deadline);
   fs.writeFileSync(path.join(evidenceDirectory,'operation-failure.json'),JSON.stringify({kind,samples},null,2));
   throw error;
  }
 };
 const oldRuns=await checked(`/tasks/${shellTask.id}/runs`),oldRun=oldRuns.find(r=>r.status==='SUCCESS'),oldLog=(await checked(`/task-runs/${oldRun.id}/log`)).content;
 const oldTriggers=await checked(`/tasks/${shellTask.id}/triggers`),oldHealth=await checked(`/tasks/${shellTask.id}/health`),oldDeliveries=await checked('/notification-deliveries');
 const repos=await checked('/repositories');const bare=path.join(env.QL_DATA_DIR,'git',repos[0].host,`repository-${repos[0].id}.git`);
 const local=(...args)=>execFileSync('git',args,{stdio:'pipe',env:{...process.env,GIT_AUTHOR_NAME:'Backup Fixture',GIT_AUTHOR_EMAIL:'fixture@example.test',GIT_COMMITTER_NAME:'Backup Fixture',GIT_COMMITTER_EMAIL:'fixture@example.test'}}).toString().trim();
 // A separate local-only branch protects operator data without preventing subscription fast-forward.
 const head=local('--git-dir',bare,'rev-parse','refs/remotes/origin/main'),tree=local('--git-dir',bare,'rev-parse',head+'^{tree}');const localCommit=local('--git-dir',bare,'commit-tree',tree,'-p',head,'-m','unpublished backup fixture');local('--git-dir',bare,'update-ref','refs/heads/backup-local-only',localCommit);local('--git-dir',bare,'update-ref','refs/tags/backup-local-tag',localCommit);
 const taskDetail=await checked(`/tasks/${shellTask.id}`),wt=path.join(env.QL_DATA_DIR,'worktrees',`repository-${repos[0].id}`,`wt-${taskDetail.source.worktree_id}`);
 fs.writeFileSync(path.join(wt,'backup-untracked'),'UNTRACKED_BACKUP_DATA',{mode:0o644});fs.appendFileSync(path.join(wt,'job.sh'),'\n# DIRTY_BACKUP_DATA\n');fs.symlinkSync('backup-untracked',path.join(wt,'backup-safe-link'));
 await backupPage();await page.getByRole('button',{name:'创建备份',exact:true}).click();await waitOperation('SNAPSHOT');const snapshot=(await checked('/backups'))[0];assert.equal(snapshot.status,'READY');mark('browser-create-consistent-ready-backup');
 await page.getByRole('button',{name:/详\s*情/}).first().click();await page.getByRole('dialog',{name:'备份详情'}).waitFor();await page.getByRole('dialog',{name:'备份详情'}).getByRole('button',{name:'Close'}).click();await page.getByRole('button',{name:/^验\s*证$/}).first().click();await waitOperation('VALIDATE');
 await page.getByRole('button',{name:'加密导出',exact:true}).first().click();let modal=page.getByRole('dialog',{name:'加密导出',exact:true});await modal.getByLabel('加密口令',{exact:true}).fill(acceptance.secret('UNIQUE_SUPER_SECRET_BACKUP_PASSPHRASE'));await modal.getByLabel('确认口令',{exact:true}).fill(acceptance.secret('UNIQUE_SUPER_SECRET_BACKUP_PASSPHRASE'));await modal.getByRole('button',{name:/确.*定|OK/}).click();await waitOperation('EXPORT');const downloading=page.waitForEvent('download');await page.getByRole('button',{name:'下载加密备份',exact:true}).click();const download=await downloading,file=path.join(tmp,'disaster.platform-backup');await download.saveAs(file);fs.chmodSync(file,0o600);assert.ok(!fs.readFileSync(file).includes(acceptance.secret('CONFIG_SECRET_E2E')));mark('browser-validate-encrypted-export-download');
 async function upload(phrase){await page.getByRole('button',{name:'导入加密备份',exact:true}).click();const modal=page.getByRole('dialog',{name:'导入加密备份',exact:true});await modal.getByLabel('备份文件',{exact:true}).setInputFiles(file);await modal.getByLabel('加密口令',{exact:true}).fill(phrase);await modal.getByRole('button',{name:/确.*定|OK/}).click();}
 await upload('wrong-secret-passphrase');await page.getByText('IMPORT: FAILED',{exact:true}).waitFor();mark('browser-import-wrong-passphrase-rejected');await upload(acceptance.secret('UNIQUE_SUPER_SECRET_BACKUP_PASSPHRASE'));await waitOperation('IMPORT');await page.getByRole('button',{name:'验证导入',exact:true}).click();await waitOperation('VALIDATE_IMPORT');await page.getByRole('button',{name:'暂存恢复',exact:true}).click();modal=page.getByRole('dialog',{name:'确认恢复',exact:true});await modal.getByLabel('输入 RESTORE',{exact:true}).fill('RESTORE');await modal.getByRole('button',{name:/确.*定|OK/}).click();await waitOperation('STAGE_RESTORE');assert.equal((await checked('/restore/status')).stage,'PENDING');await page.screenshot({path:path.join(evidenceDirectory, 'browser-restore-pending.png'),fullPage:true});mark('browser-import-stage-restore-pending');
 await stop();await start();await page.evaluate(()=>localStorage.removeItem('token'));await page.goto(base+'/login');await login();assert.equal((await checked('/restore/status')).stage,'COMPLETE');mark('real-backend-restart-applies-staged-restore');
 await stop();const original=env.QL_DATA_DIR;fs.rmSync(original,{recursive:true});fs.renameSync(origin,origin+'-offline');env.QL_DATA_DIR=path.join(tmp,'restored-B');
 const backupPhrase=acceptance.secret('UNIQUE_SUPER_SECRET_BACKUP_PASSPHRASE');
 const cli=(...args)=>JSON.parse(execFileSync(process.execPath,[path.join(root,'static/build/backupCli.js'),...args],{env,cwd:root,stdio:['pipe','pipe','pipe'],input:backupPhrase}).toString());
 const imported=cli('import',file).data.import_id;cli('stage',imported,'--import');await start();await page.evaluate(()=>localStorage.removeItem('token'));await page.goto(base+'/login');await login();assert.equal((await checked('/restore/status')).stage,'COMPLETE');assert.ok(!fs.existsSync(original));mark('destroy-original-offline-import-startup-restore-different-root');
 const restoredWt=path.join(env.QL_DATA_DIR,path.relative(original,wt)),restoredBare=path.join(env.QL_DATA_DIR,path.relative(original,bare));assert.equal(local('--git-dir',restoredBare,'rev-parse','backup-local-only'),localCommit);assert.equal(local('--git-dir',restoredBare,'rev-parse','backup-local-tag'),localCommit);assert.match(fs.readFileSync(path.join(restoredWt,'job.sh'),'utf8'),/DIRTY_BACKUP_DATA/);assert.equal(fs.readlinkSync(path.join(restoredWt,'backup-safe-link')),'backup-untracked');assert.equal(fs.readFileSync(path.join(restoredWt,'backup-untracked'),'utf8'),'UNTRACKED_BACKUP_DATA');assert.match(local('-C',restoredWt,'status','--porcelain'),/job.sh/);mark('local-only-git-dirty-untracked-symlink-preserved-with-origin-unavailable');
 const afterTriggers=await checked(`/tasks/${shellTask.id}/triggers`);const stableTrigger=t=>[t.id,t.type,t.type==='CRON'?Object.fromEntries(Object.entries(t.config).filter(([key])=>!['last_fire_at','next_fire_at','updatedAt'].includes(key))):t.config];assert.deepEqual(afterTriggers.map(stableTrigger),oldTriggers.map(stableTrigger));assert.equal((await checked(`/tasks/${shellTask.id}/health`)).consecutive_failures,oldHealth.consecutive_failures);assert.ok((await checked('/notification-deliveries')).length>=oldDeliveries.length);assert.equal((await checked(`/task-runs/${oldRun.id}/log`)).content,oldLog);
 for(const language of ['python','node'])assert.ok((await checked(`/runtime/${language}/installations`)).every(r=>r.state==='MISSING'));
 await page.goto(base+`/runs?run=${oldRun.id}`);modal=page.getByRole('dialog',{name:`Run ${oldRun.id}`,exact:true});await modal.getByRole('tab',{name:'Logs',exact:true}).click();await until(async()=>(await modal.getByTestId('run-log').innerText()).length>0);await page.screenshot({path:path.join(evidenceDirectory, 'browser-restored-history-log.png'),fullPage:true});mark('restored-history-health-trigger-identities-and-browser-old-log');
 await backupPage();await page.getByRole('button',{name:'重建缺失的托管资源',exact:true}).click();await waitOperation('REBUILD');mark('explicit-managed-python-node-and-environment-rebuild');
 for(const task of tasks){const readiness=await checked(`/tasks/${task.id}/validate`,'POST');assert.equal(readiness.readiness.status,'READY');const r=await checked(`/tasks/${task.id}/run`,'POST',{source:'MANUAL'});await until(async()=>!['QUEUED','RESOLVING','RUNNING'].includes((await checked(`/task-runs/${r.id}`)).status));assert.equal((await checked(`/task-runs/${r.id}`)).status,'SUCCESS');}mark('restored-managed-python-node-shell-tasks-execute');
 const response=await fetch(base+'/hooks/'+hook.config.public_id,{method:'POST',headers:{authorization:'Bearer '+hook.secret}});assert.equal(response.status,202);const webhook=await response.json();await until(async()=>(await checked(`/task-runs/${webhook.run_id}`)).status==='SUCCESS');mark('restored-webhook-original-secret-executes');
 const current=(await checked(`/tasks/${shellTask.id}/triggers`)).find(t=>t.id===cron.id);const enabled=await checked(`/tasks/${shellTask.id}/triggers/${cron.id}`,'PUT',{type:'CRON',enabled:true,expected_version:current.version,config:{expression:'*/2 * * * * *',timezone:'Asia/Singapore'}});const previous=(await checked(`/tasks/${shellTask.id}/runs`))[0].id;await until(async()=>(await checked(`/tasks/${shellTask.id}/runs`)).some(r=>r.id>previous&&r.status==='SUCCESS'));await checked(`/tasks/${shellTask.id}/triggers/${cron.id}`,'PUT',{type:'CRON',enabled:false,expected_version:enabled.version,config:{expression:'*/2 * * * * *',timezone:'Asia/Singapore'}});mark('restored-cron-executes');
 // Restore operator dirt before deliberately exercising a new remote transition.
 local('-C',restoredWt,'restore','job.sh');for(const file of ['backup-untracked','backup-safe-link','.retry-marker'])fs.rmSync(path.join(restoredWt,file),{force:true});assert.equal(local('-C',restoredWt,'status','--porcelain'),'');fs.renameSync(origin+'-offline',origin);fs.appendFileSync(path.join(origin,'job.sh'),'\n# phase14 after recovery\n');git('add','.');git('commit','-qm','phase14 after recovery');const commit=git('rev-parse','HEAD').toString().trim();await page.goto(base+'/subscription');await page.getByRole('row').filter({hasText:'E2E Subscription'}).getByText('运行',{exact:true}).click();await page.locator('.ant-modal:visible').getByRole('button',{name:/确.*定|OK/}).click();await until(async()=>{const event=(await checked(`/tasks/${shellTask.id}/trigger-events`)).find(e=>e.trigger_id===gitTrigger.id&&e.metadata.after===commit&&e.task_run_id);return event&&(await checked(`/task-runs/${event.task_run_id}`)).status==='SUCCESS';});mark('restored-git-new-transition-executes');
 const policy=await checked(`/tasks/${shellTask.id}/notification-policy`);async function configure(arg){const task=await checked(`/tasks/${shellTask.id}`);await checked(`/tasks/${task.id}`,'PUT',{name:task.name,enabled:true,arguments:[arg],expected_version:task.version,source:Object.fromEntries(['type','worktree_id','relative_entrypoint','language','cwd_mode','cwd_relative_path'].map(k=>[k,task.source[k]])),runtime:{kind:'SHELL'},settings:{concurrency:'QUEUE',max_attempts:1}});}
 async function run(){const r=await checked(`/tasks/${shellTask.id}/run`,'POST',{source:'MANUAL'});await until(async()=>!['QUEUED','RESOLVING','RUNNING'].includes((await checked(`/task-runs/${r.id}`)).status));}
 const failureCount=messages.filter(m=>m.event==='FAILED').length,recoveryCount=messages.filter(m=>m.event==='RECOVERY').length;await configure('--fail');for(let i=0;i<policy.failure_threshold;i++)await run();await until(()=>messages.filter(m=>m.event==='FAILED').length>failureCount);await configure('');await run();await until(()=>messages.filter(m=>m.event==='RECOVERY').length>recoveryCount);mark('restored-failure-and-recovery-notifications-real-http');
};
