import { Router } from 'express';
import user from './user';
import runtimeRoutes from './runtime';
import configAssets from './configAssets';
import log from './log';
import cron from './cron';
import script from './script';
import open from './open';
import dependence from './dependence';
import system from './system';
import subscription from './subscription';
import update from './update';
import dashboard from './dashboard';
import health from './health';
import clientIp from './clientIp';
import retention from './retention';
import gitResources from './gitResources';
import workspaceRoutes from './workspace';

export default () => {
  const app = Router();
  user(app);
  runtimeRoutes(app);
  configAssets(app);
  log(app);
  cron(app);
  script(app);
  open(app);
  dependence(app);
  system(app);
  workspaceRoutes(app);
  gitResources(app);
  subscription(app);
  update(app);
  dashboard(app);
  health(app);
  clientIp(app);
  retention(app);

  return app;
};
