const test=require('node:test'),assert=require('node:assert/strict');
const setup=require('../phase3/helpers.cjs');
test('failed publication retains Task Hooks, Config bindings and ENV; successful deletion cascades once',async t=>{
 const h=await setup(t),Cron=h.get('services/cron').default,service=new Cron({error(){},warn(){}});
 const task=await h.SchedulerProjectionModel.create({name:'old',command:'task subscription-1/job.sh',schedule:'0 8 * * *',sub_id:1,discovery_key:'stable',isDisabled:1});
 const hook=await h.TaskHookModel.create({task_id:task.id,name:'keep',phase:'FINALLY',command:'echo keep',position:10,failure_policy:'FAIL_EXECUTION'});const asset=await h.ConfigAssetModel.create({name:'keep asset',is_secret:false});const binding=await h.TaskConfigBindingModel.create({task_id:task.id,asset_id:asset.get('id'),operation:'ATTACH',target_base:'TASK_DIR',target_path:'config.yaml'});const variable=await h.TaskEnvVariableModel.create({task_id:task.id,name:'KEEP',value:'KEEP_VALUE',operation:'SET'});
 const original=service.setCrontab;let once=true,live='old';service.setCrontab=async(...args)=>{if(once){once=false;throw Error('scheduler failure');}return original.apply(service,args);};
 const plan=async()=>({subscriptionId:1,adds:[],updates:[],drops:[task.id],publish:async()=>{live='new';},rollback:async()=>{live='old';},cleanup:async()=>{}});
 await assert.rejects(new(h.get('services/task').default)().reconcileDiscoveredTasks(service,plan,async()=>{}));assert.equal(live,'old');assert.ok(await h.SchedulerProjectionModel.findByPk(task.id));assert.equal((await h.TaskHookModel.findByPk(hook.get('id'))).get('command'),'echo keep');assert.ok(await h.TaskConfigBindingModel.findByPk(binding.get('id')));assert.equal((await h.TaskEnvVariableModel.unscoped().findByPk(variable.get('id'))).get('value'),'KEEP_VALUE');
 service.setCrontab=original;await new(h.get('services/task').default)().reconcileDiscoveredTasks(service,plan,async()=>{});assert.equal(live,'new');assert.equal(await h.SchedulerProjectionModel.findByPk(task.id),null);for(const model of [h.TaskHookModel,h.TaskConfigBindingModel])assert.equal(await model.count({where:{task_id:task.id}}),0);assert.equal(await h.TaskEnvVariableModel.count({where:{task_id:task.id}}),0);assert.ok(await h.ConfigAssetModel.findByPk(asset.get('id')));
});
