const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs/promises'),path=require('node:path'),express=require('express'),{spawn}=require('node:child_process');
const {fixture}=require('./helpers.cjs');
test('Script HTTP access is excluded by Config SH lease and blocked by stale journals, then resumes',async t=>{
 const h=await fixture(t);await fs.mkdir(path.join(h.root,'shell'),{recursive:true});await fs.copyFile(path.resolve('shell/config_access_lease.py'),path.join(h.root,'shell/config_access_lease.py'));const protect=h.load('back/shared/scriptConfigAccess.ts').protectScriptConfigAccess;const app=express();let read=0;app.get('/script',protect(async(req,res)=>{read++;res.send('SOURCE_CONTENT');}));const server=app.listen(0,'127.0.0.1');await new Promise(r=>server.once('listening',r));t.after(()=>new Promise(r=>server.close(r)));const url=`http://127.0.0.1:${server.address().port}/script`;
 assert.equal((await fetch(url)).status,200);const lock=spawn('python3',['-I','-S','-c','import sys,fcntl; f=open(sys.argv[1],"a"); fcntl.flock(f,fcntl.LOCK_SH); print("READY",flush=True); sys.stdin.read()',path.join(h.root,'.locks/config-access.lock')]);await new Promise(r=>lock.stdout.once('data',r));const done=new Promise(r=>lock.on('close',r));try{const busy=await fetch(url);assert.equal(busy.status,409);assert.match(await busy.text(),/CONFIG_WORKSPACE_BUSY/);assert.equal(read,1);}finally{lock.stdin.end();await done;}
 const stale=path.join(h.root,'tmp/config-materialization/workspace/run-stale');await fs.mkdir(stale,{recursive:true});const denied=await fetch(url);assert.equal(denied.status,409);assert.match(await denied.text(),/CONFIG_RECOVERY_REQUIRED/);assert.equal(read,1);await fs.rmdir(stale);assert.equal((await fetch(url)).status,200);assert.equal(read,2);
});
test('Node retains API flock after helper exit through asynchronous action and response completion',async t=>{
 const h=await fixture(t);await fs.mkdir(path.join(h.root,'shell'),{recursive:true});await fs.copyFile(path.resolve('shell/config_access_lease.py'),path.join(h.root,'shell/config_access_lease.py'));const protect=h.load('back/shared/scriptConfigAccess.ts').protectScriptConfigAccess;let release,entered;const gate=new Promise(r=>release=r),started=new Promise(r=>entered=r);const app=express();app.get('/script',protect(async(req,res)=>{entered();await gate;res.send('done');}));const server=app.listen(0,'127.0.0.1');await new Promise(r=>server.once('listening',r));t.after(()=>new Promise(r=>server.close(r)));const request=fetch(`http://127.0.0.1:${server.address().port}/script`);await started;
 const probe=()=>new Promise(resolve=>{const child=spawn('python3',['-I','-S','-c','import sys,fcntl; f=open(sys.argv[1],"a");\ntry: fcntl.flock(f,fcntl.LOCK_SH|fcntl.LOCK_NB)\nexcept BlockingIOError: sys.exit(75)',path.join(h.root,'.locks/config-access.lock')]);child.on('close',resolve);});assert.equal(await probe(),75);release();assert.equal((await request).status,200);await new Promise(r=>setTimeout(r,20));assert.equal(await probe(),0);
});
